// Czech country names for the autograph-request "Země" autocomplete
// (components/CountryPicker.tsx) — plain display names, not ISO codes,
// since the field itself just stores free text (autograph_requests.country).
export const COUNTRIES: string[] = [
  "Afghánistán", "Albánie", "Alžírsko", "Andorra", "Angola", "Argentina", "Arménie",
  "Austrálie", "Ázerbájdžán", "Bahamy", "Bahrajn", "Bangladéš", "Barbados", "Belgie",
  "Belize", "Benin", "Bhútán", "Bělorusko", "Bolívie", "Bosna a Hercegovina", "Botswana",
  "Brazílie", "Brunej", "Bulharsko", "Burkina Faso", "Burundi", "Chile", "Chorvatsko",
  "Čad", "Černá Hora", "Česko", "Čína", "Dánsko", "Demokratická republika Kongo",
  "Dominika", "Dominikánská republika", "Džibutsko", "Egypt", "Ekvádor", "Eritrea",
  "Estonsko", "Eswatini", "Etiopie", "Fidži", "Filipíny", "Finsko", "Francie", "Gabon",
  "Gambie", "Ghana", "Grenada", "Gruzie", "Guatemala", "Guinea", "Guinea-Bissau",
  "Guyana", "Honduras", "Indie", "Indonésie", "Irák", "Írán", "Irsko", "Island",
  "Itálie", "Izrael", "Jamajka", "Japonsko", "Jemen", "Jihoafrická republika",
  "Jižní Korea", "Jižní Súdán", "Jordánsko", "Kambodža", "Kamerun", "Kanada", "Katar",
  "Kazachstán", "Keňa", "Kolumbie", "Komory", "Kongo", "Kostarika", "Kuba", "Kuvajt",
  "Kypr", "Kyrgyzstán", "Laos", "Lesotho", "Libanon", "Libérie", "Libye",
  "Lichtenštejnsko", "Litva", "Lotyšsko", "Lucembursko", "Madagaskar", "Maďarsko",
  "Malajsie", "Malawi", "Maledivy", "Mali", "Malta", "Maroko", "Marshallovy ostrovy",
  "Mauricius", "Mauritánie", "Mexiko", "Mikronésie", "Moldavsko", "Monako", "Mongolsko",
  "Mosambik", "Myanmar", "Namibie", "Nauru", "Německo", "Nepál", "Niger", "Nigérie",
  "Nikaragua", "Nizozemsko", "Norsko", "Nový Zéland", "Omán", "Pákistán", "Palau",
  "Palestina", "Panama", "Papua Nová Guinea", "Paraguay", "Peru", "Pobřeží slonoviny",
  "Polsko", "Portugalsko", "Rakousko", "Rovníková Guinea", "Rumunsko", "Rusko",
  "Rwanda", "Řecko", "Salvador", "Samoa", "San Marino", "Saúdská Arábie", "Senegal",
  "Severní Korea", "Severní Makedonie", "Seychely", "Sierra Leone", "Singapur",
  "Slovensko", "Slovinsko", "Somálsko", "Spojené arabské emiráty", "Spojené království",
  "Spojené státy americké", "Srbsko", "Střední africká republika", "Súdán", "Surinam",
  "Sýrie", "Šalamounovy ostrovy", "Španělsko", "Švédsko", "Švýcarsko", "Tádžikistán",
  "Tanzanie", "Thajsko", "Tchaj-wan", "Togo", "Tonga", "Trinidad a Tobago", "Tunisko",
  "Turecko", "Turkmenistán", "Tuvalu", "Uganda", "Ukrajina", "Uruguay", "Uzbekistán",
  "Vanuatu", "Vatikán", "Venezuela", "Vietnam", "Východní Timor", "Zambie", "Zimbabwe",
];
