// Temporary mock catalog — stands in for the `persons` table until the
// Supabase project exists and migration 0001 is applied. Real entries will
// carry a Wikimedia Commons portrait with author/license/source per the
// project's portrait rule; these placeholders intentionally don't, since the
// attribution data hasn't been sourced yet.
export type PersonCategory = "herec" | "hudebnik" | "sportovec" | "spisovatel" | "jine";

export type FilmographyEntry = {
  year: number;
  title: string;
  note?: string;
};

export type PriceHistoryPoint = {
  year: number;
  price: number;
};

export type SaleListing = {
  title: string;
  url: string;
};

export type MockPerson = {
  slug: string;
  name: string;
  category: PersonCategory;
  birthYear: number;
  deathYear: number | null;
  nationality: string;
  bio?: string;
  funFact?: string;
  funFactSourceUrl?: string;
  filmography?: FilmographyEntry[];
  marketPriceMin?: number;
  marketPriceMax?: number;
  priceHistory?: PriceHistoryPoint[];
  saleListings?: SaleListing[];
};

export const CATEGORY_LABELS: Record<PersonCategory, string> = {
  herec: "Herec",
  hudebnik: "Hudebník",
  sportovec: "Sportovec",
  spisovatel: "Spisovatel",
  jine: "Jiné",
};

export const CATEGORY_COLORS: Record<PersonCategory, string> = {
  herec: "#7F77DD",
  hudebnik: "#D85A30",
  sportovec: "#1D9E75",
  spisovatel: "#B08D57",
  jine: "#71717A",
};

export const MOCK_PERSONS: MockPerson[] = [
  {
    slug: "louis-de-funes",
    name: "Louis de Funès",
    category: "herec",
    birthYear: 1914,
    deathYear: 1983,
    nationality: "Francie",
    bio: "Louis de Funès se přes dvacet let živil vedlejšími a nekreditovanými rolemi, než se ve svých padesáti letech stal filmovou hvězdou díky Četníkovi ze Saint-Tropez a Fantomasovi (oba 1964). V druhé polovině 60. a v 70. letech byl nejlépe placeným a nejpopulárnějším hercem ve Francii — jeho Velký flám (1966) byl přes tři dekády nejnavštěvovanějším francouzským filmem v historii kin. Naposledy se na plátně objevil ve filmu Četník a četnice, který měl premiéru rok před jeho smrtí.",
    funFact: "Než se proslavil jako herec, živil se mimo jiné jako jazzový pianista v pařížských barech. Na vrcholu slávy se pak stal vášnivým zahradníkem — na svém zámku Clermont v Anjou vypěstoval růžovou zahradu, která dodnes patří k nejkrásnějším ve Francii a je otevřená veřejnosti.",
    marketPriceMin: 32000,
    marketPriceMax: 40000,
    priceHistory: [
      { year: 2020, price: 10000 },
      { year: 2024, price: 32000 },
    ],
    saleListings: [
      {
        title: "Louis de Funès — francouzský herec, autogram/podpis",
        url: "https://aukro.cz/louis-de-funes-francouzsky-herec-autogram-podpis-7072320906",
      },
      {
        title: "Louis de Funès — podpis a věnování na fotografii s rukopisnou obálkou",
        url: "https://aukro.cz/louis-de-funes-podpis-a-venovani-na-fotografii-s-rukopisnou-obalkou-6966525273",
      },
    ],
    filmography: [
      { year: 1982, title: "Četník a četnice" },
      { year: 1981, title: "Zelňačka" },
      { year: 1980, title: "Lakomec" },
      { year: 1979, title: "Četník a mimozemšťané" },
      { year: 1978, title: "Jeden hot a druhý čehý" },
      { year: 1976, title: "Křidýlko nebo stehýnko" },
      { year: 1973, title: "Dobrodružství rabína Jákoba" },
      { year: 1971, title: "Jo" },
      { year: 1971, title: "Na stromě" },
      { year: 1971, title: "Pošetilost mocných" },
      { year: 1970, title: "Četník ve výslužbě" },
      { year: 1970, title: "Piti Piti Pa" },
      { year: 1969, title: "Hibernatus" },
      { year: 1968, title: "Četník se žení" },
      { year: 1968, title: "Tetovaný" },
      { year: 1967, title: "Fantomas kontra Scotland Yard" },
      { year: 1967, title: "Oskar" },
      { year: 1967, title: "Senzační prázdniny" },
      { year: 1967, title: "Tonoucí se stébla chytá" },
      { year: 1966, title: "Grand restaurant pana Septima" },
      { year: 1966, title: "Velký flám" },
      { year: 1965, title: "Četník v New Yorku" },
      { year: 1965, title: "Fantomas se zlobí" },
      { year: 1965, title: "Smolař" },
      { year: 1965, title: "Velký pán" },
      { year: 1964, title: "Četník ze Saint Tropez" },
      { year: 1964, title: "Fantomas" },
      { year: 1964, title: "Jak vykrást banku" },
      { year: 1964, title: "Nebožtíci" },
      { year: 1964, title: "Une souris chez les hommes" },
      { year: 1963, title: "Karamboly" },
      { year: 1963, title: "Les Veinards" },
      { year: 1963, title: "Pouic Pouic" },
      { year: 1962, title: "Ďábel a desatero" },
      { year: 1962, title: "Gentleman z Epsomu" },
      { year: 1962, title: "Le Crime ne paie pas" },
      { year: 1962, title: "Nous irons à Deauville" },
      { year: 1962, title: "Un clair de lune a Maubeuge" },
      { year: 1961, title: "Candide ou l'optimisme au XXe siècle" },
      { year: 1961, title: "Kapitán Fracasse" },
      { year: 1961, title: "La Vendetta" },
      { year: 1961, title: "Výhodná koupě" },
      { year: 1960, title: "Certains l'aiment... froide" },
      { year: 1960, title: "Dans l'eau... qui fait des bulles !" },
      { year: 1960, title: "Les Tortillards" },
      { year: 1959, title: "Filutové" },
      { year: 1959, title: "Mon pote le gitan" },
      { year: 1959, title: "Totò v Madridu" },
      { year: 1958, title: "La Vie à deux" },
      { year: 1958, title: "Nevídáno, neslýcháno" },
      { year: 1958, title: "Taxi, maringotka a korida" },
      { year: 1957, title: "Smolař" },
      { year: 1956, title: "Bébés à gogo" },
      { year: 1956, title: "Bonjour sourire !" },
      { year: 1956, title: "La Bande à Papa" },
      { year: 1956, title: "La Puce à l'oreille", note: "TV film" },
      { year: 1956, title: "Napříč Paříží" },
      { year: 1956, title: "O délku hlavy" },
      { year: 1956, title: "Otec, matka, moje žena a já" },
      { year: 1956, title: "Si Paris nous était conté" },
      { year: 1956, title: "Zákon ulic" },
      { year: 1955, title: "Frou-Frou" },
      { year: 1955, title: "Husaři" },
      { year: 1955, title: "Ingrid - Die Geschichte eines Fotomodells" },
      { year: 1955, title: "Les Pépées font la loi" },
      { year: 1955, title: "L'Impossible Monsieur Pipelet" },
      { year: 1955, title: "Mädchen ohne Grenzen" },
      { year: 1955, title: "Napoléon" },
      { year: 1954, title: "Beránek s pěti nohama" },
      { year: 1954, title: "Escalier de service" },
      { year: 1954, title: "Faites-moi confiance" },
      { year: 1954, title: "Fraternité", note: "TV film" },
      { year: 1954, title: "Huis clos" },
      { year: 1954, title: "La Reine Margot" },
      { year: 1954, title: "Le Chevalier de la nuit" },
      { year: 1954, title: "Les Corsaires du Bois de Boulogne" },
      { year: 1954, title: "Le Secret d'Hélène Marimon" },
      { year: 1954, title: "Les Hommes ne pensent qu'à ça" },
      { year: 1954, title: "Les Impures" },
      { year: 1954, title: "Les Intrigantes" },
      { year: 1954, title: "Mam'zelle Nitouche" },
      { year: 1954, title: "Osení" },
      { year: 1954, title: "Otec, matka, služka a já" },
      { year: 1954, title: "Poisson d'avril" },
      { year: 1954, title: "Poprask v kabaretu" },
      { year: 1954, title: "Scenes de ménage" },
      { year: 1954, title: "Tourments" },
      { year: 1953, title: "Au diable la vertu" },
      { year: 1953, title: "Capitaine Pantoufle" },
      { year: 1953, title: "La Vie d'un honnête homme" },
      { year: 1953, title: "Légère et court vêtue" },
      { year: 1953, title: "Le Rire" },
      { year: 1953, title: "Les Compagnes de la nuit" },
      { year: 1953, title: "Les Dents longues" },
      { year: 1953, title: "L'Etrange Désir de monsieur Bard" },
      { year: 1953, title: "Ložnice dospívajících dívek" },
      { year: 1953, title: "Mon Frangin du Senegal" },
      { year: 1953, title: "Nevinní v Paříži" },
      { year: 1952, title: "Agence matrimoniale" },
      { year: 1952, title: "Boží soud" },
      { year: 1952, title: "Elle et moi" },
      { year: 1952, title: "Ils étaient cinq" },
      { year: 1952, title: "Je l'ai été trois fois" },
      { year: 1952, title: "La Fugue de Monsieur Perle" },
      { year: 1952, title: "La Jungle en folie" },
      { year: 1952, title: "L'Amour n'est pas un péché" },
      { year: 1952, title: "Les Loups chassent la nuit" },
      { year: 1952, title: "Les Sept Péchés capitaux" },
      { year: 1952, title: "Moineaux de Paris" },
      { year: 1952, title: "Monsieur Leguignon Lampiste" },
      { year: 1952, title: "Pan Taxi" },
      { year: 1952, title: "Počestná děvka" },
      { year: 1951, title: "Adresát neznámý" },
      { year: 1951, title: "Bibi Fricotin" },
      { year: 1951, title: "Boniface Somnambule" },
      { year: 1951, title: "Folie douce" },
      { year: 1951, title: "Knock" },
      { year: 1951, title: "L'Amant de paille" },
      { year: 1951, title: "La Poison" },
      { year: 1951, title: "La Rose rouge" },
      { year: 1951, title: "La Vie est un jeu" },
      { year: 1951, title: "Le Dindon" },
      { year: 1951, title: "Le Roi du bla bla bla" },
      { year: 1951, title: "Le Voyage en Amérique" },
      { year: 1951, title: "Ma femme est formidable" },
      { year: 1951, title: "Žádná dovolená pro pana starostu" },
      { year: 1950, title: "Adémai au poteau-frontière" },
      { year: 1950, title: "È più facile che un cammello..." },
      { year: 1950, title: "La Rue sans loi" },
      { year: 1950, title: "L'Inconnue de Montréal" },
      { year: 1950, title: "Mon ami Sainfoin" },
      { year: 1950, title: "Na shledanou, pane Grocku" },
      { year: 1950, title: "Pas de week-end pour notre amour" },
      { year: 1950, title: "Un certain monsieur" },
      { year: 1949, title: "Du Guesclin" },
      { year: 1949, title: "Je n'aime que toi" },
      { year: 1949, title: "Millionnaires d'un jour" },
      { year: 1949, title: "Mission à Tanger" },
      { year: 1949, title: "Rendez-vous avec la chance" },
      { year: 1949, title: "Vient de paraître" },
      { year: 1948, title: "Croisière pour l'inconnu" },
      { year: 1947, title: "Antoine a Antoinetta" },
      { year: 1947, title: "Dernier refuge" },
      { year: 1947, title: "Six heures à perdre" },
      { year: 1946, title: "La Tentation de Barbizon" },
    ],
  },
  {
    slug: "michel-galabru",
    name: "Michel Galabru",
    category: "herec",
    birthYear: 1922,
    deathYear: 2016,
    nationality: "Francie",
    bio: "Michel Galabru se narodil ve francouzské koloniální rodině v marockém Safi, kde jeho otec jako stavební inženýr vedl rozsáhlé stavební projekty. Po zhruba deseti letech se rodina vrátila zpět do Francie a dětství tak prožil na dvou kontinentech. Po maturitě si nejdřív vydělával jako pojišťovací agent v Paříži, souběžně ale vystudoval pařížskou konzervatoř dramatického umění jako nejlepší ze svého ročníku v oboru moderní a klasické komedie. Od září 1950 hrál klasický repertoár — Shakespeara, Molièra i Feydeaua — v proslulé Comédie-Française, než se přesunul i do kabaretu a filmu. Nejdřív bral drobné epizodní role, skutečnou slávu mu ale přinesla postava neoblomného četnického velitele Gerbera po boku Louise de Funèse ve filmové sérii o četnících ze Saint-Tropez; tenhle komický typ — navenek přísný muž lpící na pořádku a tradicích — pak formoval velkou část jeho pozdější filmografie. Kromě četnických komedií hrál i v dalších velkých titulech jako Klec bláznů, Podzemka nebo o desítky let později Vítejte u Ch'tisů a Asterix a Obelix. Za jednu z mála vážných rolí své kariéry, vyšetřujícího soudce ve snímku Soudce a vrah (1976), získal v roce 1977 Césara pro nejlepšího herce a další vážné role mu vynesly ještě dvě nominace. Za svůj život si zahrál asi ve dvou stovkách filmů, v roce 2008 získal divadelní Molièrovu cenu a v roce 2013 se stal velkodůstojníkem francouzského Národního řádu za zásluhy. Zemřel v lednu 2016 v Paříži ve věku 93 let.",
    funFact: "Než se stal hercem, chtěl být profesionálním fotbalistou — k herectví a literatuře ho nakonec přivedla jeho teta. Herectvím se pak zabývala celá jeho rodina: hercem byl i jeho bratr Marc Galabru a obě jeho děti, Jean a Emmanuelle.",
    marketPriceMin: 1000,
    marketPriceMax: 2000,
    priceHistory: [
      { year: 2023, price: 1700 },
      { year: 2024, price: 640 },
      { year: 2024, price: 2100 },
    ],
    saleListings: [
      {
        title: "Michel Galabru — autogram, originální podpis, velitel četníků",
        url: "https://aukro.cz/michel-galabru-autogram-originalni-podpis-velitel-cetniku-7056421143",
      },
      {
        title: "Michel Galabru — originální autogram, podpis, větší formát",
        url: "https://aukro.cz/michel-galabru-originalni-autogram-podpis-vetsi-format-7048861369",
      },
      {
        title: "Michel Galabru — originální autogram, podpis, větší formát",
        url: "https://aukro.cz/michel-galabru-originalni-autogram-podpis-vetsi-format-7055813842",
      },
    ],
    filmography: [
      { year: 2011, title: "Le Grand restaurant II", note: "TV film" },
      { year: 2010, title: "Un poison violent" },
      { year: 2010, title: "Mumu" },
      { year: 2009, title: "Můj život v Neuilly" },
      { year: 2009, title: "Mikulášovy patálie" },
      { year: 2008, title: "Vítejte u Ch'tisů" },
      { year: 2008, title: "La Jeune fille et les loups" },
      { year: 2004, title: "San Antonio" },
      { year: 2000, title: "Herci" },
      { year: 1999, title: "Asterix a Obelix" },
      { year: 1996, title: "Můj pasák" },
      { year: 1992, title: "Belle epoque" },
      { year: 1990, title: "Uranus" },
      { year: 1989, title: "Francouzská revoluce", note: "TV film" },
      { year: 1987, title: "Rozmařilý život Gérarda Floqua" },
      { year: 1987, title: "Pěstuj si pravačku" },
      { year: 1986, title: "Nenávidím herce" },
      { year: 1986, title: "Kamikaze" },
      { year: 1985, title: "Tranches de vie" },
      { year: 1985, title: "Telefon zvoní vždycky dvakrát" },
      { year: 1985, title: "Ptačí klec 3: Svatba" },
      { year: 1985, title: "Podzemka" },
      { year: 1984, title: "Náš příběh" },
      { year: 1983, title: "Vražedné léto" },
      { year: 1983, title: "Dědoušek se dal na odboj" },
      { year: 1982, title: "Četník a četnice" },
      { year: 1981, title: "Volba zbraní" },
      { year: 1980, title: "Únos aut" },
      { year: 1980, title: "Nenapravitelní" },
      { year: 1980, title: "Lakomec" },
      { year: 1980, title: "Klec bláznů II" },
      { year: 1980, title: "Kašpárek" },
      { year: 1980, title: "Jsem fotogenický" },
      { year: 1979, title: "Zpověď jen pro sebe" },
      { year: 1979, title: "Policajt nebo rošťák" },
      { year: 1979, title: "Čtyři na kanapi", note: "TV film" },
      { year: 1979, title: "Četník a mimozemšťané" },
      { year: 1979, title: "Ciao, les mecs" },
      { year: 1978, title: "Láska s otazníkem" },
      { year: 1978, title: "Klec bláznů" },
      { year: 1977, title: "Stepující stonožka" },
      { year: 1977, title: "Skupinový portrét s dámou" },
      { year: 1977, title: "Il Gatto" },
      { year: 1976, title: "Vrátný od Maxima" },
      { year: 1976, title: "Soudce a vrah" },
      { year: 1974, title: "Letní hosté" },
      { year: 1974, title: "Dvě dívky v jednom pyžamu" },
      { year: 1973, title: "Životní šance" },
      { year: 1973, title: "Velký bazar" },
      { year: 1973, title: "Kufr na slunci" },
      { year: 1973, title: "Krysy z temnot" },
      { year: 1973, title: "Domovník" },
      { year: 1972, title: "Veselí chlapíci" },
      { year: 1972, title: "Le Viager" },
      { year: 1972, title: "Elle cause plus, elle flingue" },
      { year: 1971, title: "Trampoty s kohoutem" },
      { year: 1971, title: "Jo" },
      { year: 1970, title: "Četník ve výslužbě" },
      { year: 1968, title: "Četník se žení" },
      { year: 1967, title: "Tonoucí se stébla chytá" },
      { year: 1966, title: "Protigangová brigáda" },
      { year: 1966, title: "Angelika a král" },
      { year: 1965, title: "Četník v New Yorku" },
      { year: 1964, title: "Četník ze Saint-Tropez" },
      { year: 1962, title: "Zlatý salamandr" },
      { year: 1962, title: "Nous irons à Deauville" },
      { year: 1962, title: "Knoflíková válka" },
      { year: 1961, title: "Amours célèbres" },
      { year: 1959, title: "Les Trois mousquetaires", note: "TV film" },
    ],
  },
  {
    slug: "jean-lefebvre",
    name: "Jean Lefebvre",
    category: "herec",
    birthYear: 1919,
    deathYear: 2004,
    nationality: "Francie",
    bio: "Jean Marcel Lefebvre se narodil ve francouzském Valenciennes a původně studoval medicínu — studia mu ale přerušila druhá světová válka, během níž padl do zajetí. Po válce nastoupil na konzervatoř v oboru opera, zpěv ho ale nakonec nezaujal tolik jako herectví, na které se pak přeorientoval. Po škole hrál hlavně v kabaretech a před filmovou kamerou se poprvé objevil až v roce 1952, v muzikálu Bouquet po boku zpěváka Charlese Treneta. S Louisem de Funèsem se ve filmech potkával už předtím, než se z něj stala komická hvězda číslo jedna (Výhodná koupě, Gentleman z Epsomu, Jak vykrást banku), a jejich spolupráce pak vyvrcholila rolí četníka Luciena Fougasse ve čtyřech dílech slavné série o četnících ze Saint-Tropez. Za svůj život natočil přes sto dvacet filmů, přesto zůstal především divadelním hercem. Zemřel v roce 2004 v marockém Marrákeši, kde ho v jedné z restaurací postihl infarkt.",
    funFact: "Než se stal hercem, studoval postupně medicínu a operní zpěv — k herectví se dostal až jako ke třetí volbě. V soukromém životě pak sbíral svatby: celkem se ženil pětkrát a měl pět dětí, přičemž jednu z partnerek si vzal a rozvedl hned dvakrát po sobě v průběhu 70. let.",
    marketPriceMin: 900,
    marketPriceMax: 1700,
    priceHistory: [
      { year: 2021, price: 800 },
      { year: 2021, price: 1050 },
    ],
    saleListings: [
      {
        title: "Jean Lefebvre — autogram",
        url: "https://aukro.cz/jean-lefebrve-autogram-6986385410",
      },
      {
        title: "Jean Lefebvre (1919–2004) — originální podpis",
        url: "https://aukro.cz/jean-lefebvre-1919-2004-original-6995877739",
      },
    ],
    filmography: [
      { year: 1977, title: "Sedmá rota za úplňku" },
      { year: 1977, title: "Učitel zpěvu" },
      { year: 1976, title: "Situace je vážná, nikoliv však zoufalá" },
      { year: 1976, title: "Vrátný od Maxima" },
      { year: 1975, title: "Návrat sedmé roty" },
      { year: 1973, title: "Muž z Acapulca" },
      { year: 1973, title: "Kam se poděla sedmá rota?" },
      { year: 1972, title: "Island" },
      { year: 1970, title: "Četník ve výslužbě" },
      { year: 1968, title: "Četník se žení" },
      { year: 1967, title: "Idiot v Paříži" },
      { year: 1967, title: "Blázen z laboratoře 4" },
      { year: 1966, title: "Angelika a král" },
      { year: 1965, title: "Četník v New Yorku" },
      { year: 1964, title: "Relax" },
      { year: 1964, title: "Četník ze Saint Tropez" },
      { year: 1963, title: "Jak vykrást banku" },
      { year: 1963, title: "Tetované figury" },
      { year: 1962, title: "Konga Yo" },
    ],
  },
  {
    slug: "genevieve-gradova",
    name: "Geneviève Gradová",
    category: "herec",
    birthYear: 1944,
    deathYear: 2024,
    nationality: "Francie",
    bio: "Geneviève Gradová (rodným jménem Geneviève Gabrielle Grad) se narodila v Paříži matce architektce a jako mladá dívka se připravovala na dráhu tanečnice na pařížské opeře, než ji objevili filmaři. V sedmnácti letech dostala roli Isabelle po boku Jeana Maraise ve snímku Kapitán Fracasse (1961) a o pár let později se ucházela i o hlavní roli v Angelice, markýze andělů — tu ale nakonec získala Michèle Mercier. Životní roli si nakonec přesto zahrála: rošťáckou dceru četníka Cruchota, Nicole, v prvních třech dílech slavné série o četnících ze Saint-Tropez (1964–1968). Po natáčení Četník se žení si ale uvědomila, že si dvanáct let nevzala pořádnou dovolenou, a s náhlou slávou se jí přitížilo i psychicky — z filmového světa se proto stáhla a v dalších dílech série se už neobjevila. Ještě si zahrála v pár dalších snímcích (Flash Love, Libertés sexuelles) a naposledy stanula před kamerou v roce 1983. Poté pracovala jako obchodnice se starožitnostmi a spolu s Annie Chaplin, dcerou Charlieho Chaplina, organizovala kulturní akce pro město Vendôme — a i přes odchod z veřejného života dál dostávala dopisy s žádostmi o autogram od fanoušků z celého světa. Zemřela v listopadu 2024 ve věku 80 let po dlouhém boji s rakovinou.",
    funFact: "Její zasnoubení s Olivierem de Montalem skončilo poté, co ji seznámil se svými kamarády, dvojčaty Igorem a Grichkou Bogdanoffovými, kteří tehdy žili na rodinném zámečku Saint-Lary. Geneviève se do Igora zamilovala, v roce 1976 se jim narodil syn Dimitri a nějakou dobu žila přímo na jejich panství — stala se dokonce asistentkou produkce jejich tehdy kultovního televizního pořadu Temps X, díky němuž patřili bratři Bogdanoffové k nejznámějším televizním tvářím osmdesátých let ve Francii. Vztah s Igorem ale postupem času vychladl, otcovství přestal brát vážně a se synem se dál nestýkal. Bratři se navíc proslavili i chorobnou závislostí na plastické chirurgii, kvůli které byli ke konci života téměř nepoznatelní, a zemřeli na covid jen pár dní po sobě. Dimitri sám na veřejnosti nevystupuje a není ani jisté, čí příjmení nosí. Geneviève se pak v 90. letech provdala za architekta Jeana Guillaumea, který jí zůstal po boku až do konce života.",
    funFactSourceUrl:
      "https://medium.seznam.cz/clanek/lucie-stiborova-genevieve-grad-dcera-cetnika-cruchota-milovala-monstrum-o-angeliku-prisla-slava-ji-nicila-299820",
    marketPriceMin: 900,
    marketPriceMax: 1600,
    priceHistory: [
      { year: 2023, price: 802 },
      { year: 2023, price: 335 },
      { year: 2025, price: 1555 },
    ],
    saleListings: [
      {
        title: "Geneviève Grad — autogram",
        url: "https://aukro.cz/autogram-genevieve-grad-7047545863",
      },
      {
        title: "Geneviève Grad — originální autogram, série četníků s Louisem de Funèsem",
        url: "https://aukro.cz/genevieve-grad-originalni-autogram-serie-cetniku-louis-de-funes-7090271274",
      },
    ],
    filmography: [
      { year: 1983, title: "Ça va pas être triste" },
      { year: 1980, title: "Voulez-vous un bébé Nobel?" },
      { year: 1980, title: "La Pharisienne" },
      { year: 1980, title: "La Vie des autres" },
      { year: 1980, title: "Comme une femme" },
      { year: 1978, title: "Voltaire" },
      { year: 1977, title: "Le Maestro" },
      { year: 1977, title: "Libertés sexuelles" },
      { year: 1975, title: "Flash Love" },
      { year: 1975, title: "Au théâtre ce soir" },
      { year: 1972, title: "Flash Love" },
      { year: 1970, title: "OSS 117 prend des vacances" },
      { year: 1970, title: "Palais des anges érotiques et des plaisirs secrets" },
      { year: 1969, title: "Agence intérim" },
      { year: 1968, title: "Četník se žení" },
      { year: 1968, title: "Le Démoniaque" },
      { year: 1967, title: "Au théâtre ce soir" },
      { year: 1967, title: "Quand la liberté venait du ciel" },
      { year: 1967, title: "Le Fossé" },
      { year: 1966, title: "Su nombre es Daphne" },
      { year: 1965, title: "Četník v New Yorku" },
      { year: 1965, title: "Frédéric le gardian" },
      { year: 1965, title: "Chambre à louer" },
      { year: 1964, title: "L'Enlèvement d'Antoine Bigut" },
      { year: 1964, title: "Četník ze Saint Tropez" },
      { year: 1964, title: "Alerte à Gibraltar" },
      { year: 1963, title: "Sandokan - Le Tigre de Bornéo" },
      { year: 1963, title: "Héros de Babylone" },
      { year: 1963, title: "Hercule contre Moloch" },
      { year: 1962, title: "L'Empire de la nuit" },
      { year: 1962, title: "Les Vikings attaquent" },
      { year: 1962, title: "Arsène Lupin contre Arsène Lupin" },
      { year: 1962, title: "La bataille de Corinthe" },
      { year: 1961, title: "Un soir sur la plage" },
      { year: 1961, title: "Kapitán Fracasse" },
      { year: 1959, title: "Les dragueurs" },
    ],
  },
  {
    slug: "christian-marin",
    name: "Christian Marin",
    category: "herec",
    birthYear: 1929,
    deathYear: 2012,
    nationality: "Francie",
    bio: "Christian Marin (celým jménem Christian Bernard Georges Marin) se narodil v Lyonu, kde po studiu na Beaux-Arts nastoupil na tamní konzervatoř. V roce 1951 mu přítel Fernand Ledoux poradil zkusit konkurz do Comédie-Française — neuspěl, zato se přidal k divadelní společnosti Jeana Vilara TNP, kde se poznal s Danielem Soranem a Gérardem Philipem, a od roku 1953 dva roky hrál v Comédie de Saint-Étienne. Pak zkoušel štěstí jako komik v pařížských kabaretech, než v roce 1963 prorazil ve filmu Pouic-Pouic po boku Louise de Funèse. Mezi lety 1964 a 1970 ztvárnil strážmistra Alberta Merlota, jednoho z Cruchotových podřízených, ve všech prvních čtyřech dílech série o četnících ze Saint-Tropez — příhodně, jeho vlastní dědeček byl také četník. Na pátý díl, Četník a mimozemšťané (1978), už ale nekývl: dostal nabídku na divadelní roli od Jeana Anouilha a cítil, že už má četnické role za sebou. Divadlo bylo ostatně po celou kariéru jeho hlavní láskou — zahrál si ve zhruba čtyřiceti hrách klasického i bulvárního repertoáru a ještě v roce 2010 vystupoval v inscenaci Le Gang des Seniors. Souběžně natočil kolem padesáti filmů (mimo jiné u Clauda Autant-Lary, Costy-Gavrase nebo Yvese Roberta) a mezi lety 1967 a 1970 ztvárnil v televizním seriálu Rytíři nebes (Les Chevaliers du ciel) poručíka Ernesta Laverdura, sukničkářského, ale vynikajícího pilota. Naposledy se objevil na plátně v roce 2012 ve filmu Dead Man Talking, jen pár měsíců před svou smrtí. Zemřel na rakovinu v Paříži v září 2012 ve věku 83 let, pár týdnů po dokončení svých pamětí Mémoires d'un chevalier du ciel.",
    funFact: "Se svou ženou Monique, se kterou měl čtyři děti, zůstal ženatý skoro šedesát let. Během natáčení Četníka ze Saint-Tropez patřil mezi tajné obdivovatele mladičké Geneviève Grad — skládal jí básničky a nosil drobné dárky, ona ale měla oči jen pro asistenta režie Marca Simenona, syna spisovatele Georgese Simenona. Na svého filmového šéfa Louise de Funèse vzpomínal roky dost nejednoznačně: jednou si stěžoval, že „nevydýchal jeho hrubé chování“, jindy ho zase chválil jako zdvořilého a upřímného muže, který ho podle doslechu na place opravdu měl rád. Při pohřbu mu nad hřbitovem v Ermenonville vzdala hold dvojice stíhaček Alpha Jet — poslední pocta muži, který ztvárnil pilota Ernesta Laverdura.",
    funFactSourceUrl:
      "https://medium.seznam.cz/clanek/lucie-stiborova-christian-marin-podlezavy-cetnik-merlot-miloval-nicole-cruchot-mel-ctyri-deti-a-stihacky-nad-rakvi-305517",
    marketPriceMin: 400,
    marketPriceMax: 900,
    priceHistory: [{ year: 2022, price: 310 }],
    saleListings: [
      {
        title: "Christian Marin — autogram",
        url: "https://aukro.cz/autogram-christian-marin-7020685554",
      },
    ],
    filmography: [
      { year: 2012, title: "Dead Man Talking" },
      { year: 1986, title: "Fievel et le nouveau monde", note: "dabing" },
      { year: 1984, title: "Neuville ma belle" },
      { year: 1980, title: "Prune des bois" },
      { year: 1978, title: "Bambi", note: "dabing" },
      { year: 1977, title: "Winnie l'ourson et le Tigre fou", note: "dabing" },
      { year: 1976, title: "La Grande Récré" },
      { year: 1976, title: "Deux cloches dans la neige" },
      { year: 1975, title: "Le Commando des chauds lapins" },
      { year: 1974, title: "Commissariat de nuit" },
      { year: 1974, title: "Y'a un os dans la moulinette" },
      { year: 1973, title: "La Dernière Bourrée à Paris" },
      { year: 1970, title: "Le Gendarme en balade" },
      { year: 1970, title: "Michel Strogoff" },
      { year: 1969, title: "L'Auvergnat et l'autobus" },
      { year: 1969, title: "Faites donc plaisir aux amis" },
      { year: 1968, title: "La Permission" },
      { year: 1968, title: "Le Mois le plus beau" },
      { year: 1968, title: "Le gendarme se marie" },
      { year: 1967, title: "Les Chevaliers du ciel", note: "TV seriál, 1967–1970" },
      { year: 1966, title: "Monsieur le président-directeur général" },
      { year: 1966, title: "Monnaie de singe" },
      { year: 1965, title: "Le Chant du monde" },
      { year: 1965, title: "L'Or du duc" },
      { year: 1965, title: "Compartiment tueurs" },
      { year: 1965, title: "Dis-moi qui tuer" },
      { year: 1965, title: "Le Gendarme à New York" },
      { year: 1965, title: "Les Copains" },
      { year: 1964, title: "Allez France !" },
      { year: 1964, title: "Le Gendarme de Saint-Tropez" },
      { year: 1963, title: "Bébert et l'Omnibus" },
      { year: 1963, title: "Le Magot de Josefa" },
      { year: 1963, title: "L'Honorable Stanislas, agent secret" },
      { year: 1963, title: "Le commissaire mène l'enquête" },
      { year: 1963, title: "L'Abominable Homme des douanes" },
      { year: 1963, title: "Cherchez l'idole" },
      { year: 1963, title: "La Foire aux cancres" },
      { year: 1963, title: "Pouic-Pouic" },
      { year: 1962, title: "Comment réussir en amour" },
      { year: 1962, title: "Le crime ne paie pas" },
      { year: 1962, title: "La Gamberge" },
      { year: 1961, title: "Une blonde comme ça" },
      { year: 1961, title: "Tout l'or du monde" },
      { year: 1961, title: "La Belle Américaine" },
      { year: 1961, title: "Le Capitaine Fracasse" },
      { year: 1961, title: "Le Tracassin" },
      { year: 1960, title: "Les Tortillards" },
      { year: 1957, title: "Nous autres à Champignol" },
      { year: 1957, title: "Ces dames préfèrent le mambo" },
    ],
  },
  {
    slug: "guy-grosso",
    name: "Guy Grosso",
    category: "herec",
    birthYear: 1933,
    deathYear: 2001,
    nationality: "Francie",
    bio: "Guy Grosso, vlastním jménem Guy Marcel Sarrazin, se narodil v Beauvais. Od konce padesátých let tvořil s hercem Michelem Modem populární komediální dvojici Grosso a Modo, se kterou se objevil v řadě filmů Louise de Funèse — mimo jiné i v sérii o četnících ze Saint-Tropez, kde hrál strážmistra Gastona Tricarda. Kromě filmu se věnoval i divadlu, kde s Modem uváděl i vlastní autorské komedie, například Les Coucous. Zemřel v roce 2001 ve věku 67 let a je pohřben na hřbitově v Levallois-Perret.",
    funFact: "Guy Grosso a Michel Modo netvořili jen filmové duo — spolu psali i divadelní hry (Les Coucous) a společně vystupovali i v desítkách televizních pořadů Jeana-Christopha Averta mezi lety 1964 a 1982.",
    filmography: [
      { year: 1991, title: "Robinson et compagnie", note: "dabing" },
      { year: 1983, title: "Y a-t-il un pirate sur l'antenne ?" },
      { year: 1982, title: "Le Gendarme et les Gendarmettes" },
      { year: 1982, title: "Salut, j'arrive" },
      { year: 1980, title: "L'Avare" },
      { year: 1980, title: "Les Phallocrates" },
      { year: 1979, title: "Charles et Lucie" },
      { year: 1979, title: "Le Gendarme et les Extraterrestres" },
      { year: 1977, title: "Le mille-pattes fait des claquettes" },
      { year: 1977, title: "2 cloches dans la neige" },
      { year: 1977, title: "Ne me touchez pas..." },
      { year: 1975, title: "Chobizenesse" },
      { year: 1975, title: "Opération Lady Marlène" },
      { year: 1973, title: "L'Histoire très bonne et très joyeuse de Colinot Trousse-Chemise" },
      { year: 1970, title: "Le Gendarme en balade" },
      { year: 1970, title: "Le Champignon" },
      { year: 1969, title: "La Honte de la famille" },
      { year: 1968, title: "Le Gendarme se marie" },
      { year: 1967, title: "Les Grandes Vacances" },
      { year: 1966, title: "La Grande Vadrouille" },
      { year: 1966, title: "Le Grand Restaurant" },
      { year: 1965, title: "Le Gendarme à New York" },
      { year: 1965, title: "Les Bons Vivants" },
      { year: 1965, title: "Pleins feux sur Stanislas" },
      { year: 1965, title: "Le Corniaud" },
      { year: 1965, title: "Moi et les hommes de quarante ans" },
      { year: 1964, title: "Les Gorilles" },
      { year: 1964, title: "Le Gendarme de Saint-Tropez" },
      { year: 1964, title: "Des pissenlits par la racine" },
      { year: 1964, title: "Une ravissante idiote" },
      { year: 1964, title: "Cherchez l'idole" },
      { year: 1964, title: "Faites sauter la banque" },
      { year: 1963, title: "Bébert et l'Omnibus" },
      { year: 1963, title: "La Foire aux cancres" },
      { year: 1963, title: "Le Magot de Josefa" },
      { year: 1962, title: "Le Procès" },
      { year: 1961, title: "La Belle Américaine" },
      { year: 1959, title: "Le Petit Prof" },
    ],
  },
  {
    slug: "france-rumilly",
    name: "France Rumilly",
    category: "herec",
    birthYear: 1939,
    deathYear: null,
    nationality: "Francie",
    bio: "France Rumilly, celým jménem Marie-Françoise Suzanne Jeanne Rumilly, se narodila v Boulogne-Billancourt. Značnou část školních let strávila v klášteře, později studovala herectví a na konkurzu ji objevil režisér Jack Pinoteau, který jí v roce 1962 svěřil roli dcery Louise de Funèse ve filmu Výhodná koupě. Nejznámější se ale stala jako sestra Klotylda, věčně rozjívená jeptiška na motorové dvoukolce Citroën 2CV, v prvních třech dílech série o četnících ze Saint-Tropez — kaskadérské scény za ni odjížděl Rémy Julienne. Objevila se i v dalších filmech s Louisem de Funèsem, například v Grand restaurantu pana Septima jako baronka. Naposledy stanula před kamerou v roce 1986 ve filmu Twist again à Moscou, ve svých sedmačtyřiceti letech. Za kariéru si zahrála přibližně v pětadvaceti filmech a v mnoha dalších dělala drobnou komparzní roli — celkem se objevila ve více než dvou stovkách filmů mezi lety 1960 a 1999.",
    funFact: "Její slavná scéna s dvoukolkou 2CV z filmu Četník a četnice posloužila v roce 2010 dokonce jako inspirace pro francouzskou reklamní kampaň automobilky Citroën na příspěvek za starý vůz ve šrotovném.",
    filmography: [
      { year: 1986, title: "Twist again à Moscou" },
      { year: 1986, title: "Suivez mon regard" },
      { year: 1985, title: "Sac de nœuds" },
      { year: 1985, title: "Le facteur de Saint-Tropez" },
      { year: 1982, title: "Le Gendarme et les Gendarmettes" },
      { year: 1981, title: "Fais gaffe à la gaffe!" },
      { year: 1979, title: "Les Héroïnes du mal" },
      { year: 1979, title: "Le Gendarme et les Extraterrestres" },
      { year: 1973, title: "Je sais rien, mais je dirai tout" },
      { year: 1973, title: "Elle court, elle court la banlieue" },
      { year: 1970, title: "Le Gendarme en balade" },
      { year: 1969, title: "Salut Berthe !" },
      { year: 1969, title: "L'Auvergnat et l'Autobus" },
      { year: 1969, title: "A tout casser" },
      { year: 1968, title: "Faites donc plaisir aux amis" },
      { year: 1968, title: "Le gendarme se marie" },
      { year: 1967, title: "Playtime" },
      { year: 1966, title: "Le Solitaire passe à l'attaque" },
      { year: 1966, title: "Monsieur le président-directeur général" },
      { year: 1966, title: "Le Grand Restaurant" },
      { year: 1966, title: "Ne nous fâchons pas" },
      { year: 1965, title: "Le Gendarme à New York" },
      { year: 1965, title: "Un milliard dans un billard" },
      { year: 1965, title: "Moi et les hommes de quarante ans" },
      { year: 1964, title: "Jaloux comme un tigre" },
      { year: 1964, title: "Le Gendarme de Saint-Tropez" },
      { year: 1964, title: "Les Durs à cuire" },
      { year: 1962, title: "Les Veinards" },
    ],
  },
  {
    slug: "michel-modo",
    name: "Michel Modo",
    category: "herec",
    birthYear: 1937,
    deathYear: 2008,
    nationality: "Francie",
    bio: "Michel Modo, vlastním jménem Michel Henri Louis Goi, se narodil v Carpentras. Od konce padesátých let tvořil s Guyem Grossem legendární komediální dvojici Grosso a Modo, která se objevila v řadě filmů Louise de Funèse — v sérii o četnících ze Saint-Tropez ztvárnil strážmistra Julese Berlicota po boku Michela Galabrua, Jeana Lefebvra a Christiana Marina. Mezi lety 1993 a 1997 hrál opakující se komickou roli Maurice, karikatury typického Francouze, v americkém seriálu Highlander, a v prosinci 2005 se objevil ve francouzském seriálu Plus belle la vie jako filozofující bezdomovec převlečený za Ježíška. Druhou velkou kapitolou jeho kariéry byl dabing — od konce osmdesátých let až do své smrti daboval hned několik stálých postav v seriálu Simpsonovi (mimo jiné ředitele Skinnera, pana Burnse, Krustyho nebo policejního šéfa Wigguma). Zemřel náhle v roce 2008 ve věku 71 let, uprostřed dabování poslední řady Simpsonových — na jeho místo pak nastoupil Gérard Rinaldi, který sám zemřel o necelé čtyři roky později.",
    funFact: "Mimo herectví a dabing byl Modo i textařem — psal texty písní pro svého přítele, zpěváka Henriho Salvadora, které vyšly na jeho albech Tant de temps, Chambre avec vue nebo Ma chère et tendre.",
    filmography: [
      { year: 2006, title: "Poltergay" },
      { year: 1998, title: "Bimboland" },
      { year: 1993, title: "Pétain" },
      { year: 1990, title: "Le Château de ma mère" },
      { year: 1990, title: "La Gloire de mon père" },
      { year: 1986, title: "L'Exécutrice" },
      { year: 1983, title: "Les Planqués du régiment" },
      { year: 1983, title: "Le Braconnier de Dieu" },
      { year: 1982, title: "Le Gendarme et les Gendarmettes" },
      { year: 1981, title: "Si ma gueule vous plaît" },
      { year: 1981, title: "Les Bidasses aux grandes manœuvres" },
      { year: 1981, title: "Le jour se lève et les conneries commencent" },
      { year: 1981, title: "Pétrole ! Pétrole !" },
      { year: 1980, title: "L'Avare" },
      { year: 1979, title: "Nous maigrirons ensemble" },
      { year: 1979, title: "Le Gendarme et les Extraterrestres" },
      { year: 1978, title: "Les Bidasses au pensionnat" },
      { year: 1977, title: "Le mille-pattes fait des claquettes" },
      { year: 1977, title: "Ne me touchez pas..." },
      { year: 1975, title: "On a retrouvé la septième compagnie" },
      { year: 1975, title: "Opération Lady Marlène" },
      { year: 1973, title: "L'Histoire très bonne et très joyeuse de Colinot Trousse-Chemise" },
      { year: 1971, title: "Le Cri du cormoran le soir au-dessus des jonques" },
      { year: 1970, title: "Le Gendarme en balade" },
      { year: 1968, title: "Le Gendarme se marie" },
      { year: 1967, title: "La Grosse Pagaille" },
      { year: 1967, title: "Un homme de trop" },
      { year: 1966, title: "La Grande Vadrouille" },
      { year: 1966, title: "Le Grand Restaurant" },
      { year: 1965, title: "Le Gendarme à New York" },
      { year: 1965, title: "Pleins feux sur Stanislas" },
      { year: 1965, title: "La Tête du client" },
      { year: 1965, title: "Le Corniaud" },
      { year: 1964, title: "Les Gorilles" },
      { year: 1964, title: "Le Gendarme de Saint-Tropez" },
      { year: 1963, title: "Bébert et l'Omnibus" },
      { year: 1963, title: "Kriss Romani" },
      { year: 1963, title: "Carambolages" },
      { year: 1961, title: "Tout l'or du monde" },
      { year: 1961, title: "La Belle Américaine" },
      { year: 1959, title: "Le Petit Prof" },
    ],
  },
  {
    slug: "daniel-cauchy",
    name: "Daniel Cauchy",
    category: "herec",
    birthYear: 1930,
    deathYear: 2020,
    nationality: "Francie",
    bio: "Daniel Cauchy, vlastním jménem Daniel Raoul Simon Cauchy, se narodil v Boulogne-Billancourt. Jeho otec, prefekt na ministerstvu vnitra, zemřel, když bylo Danielovi sedm let, a matka pak syna i jeho starší sestru dala do různých internátů — vyrůstal střídavě u obou babiček mezi Lavalem a Nice. Filmovou kariéru začal roku 1951 a nakonec si zahrál ve zhruba čtyřiceti filmech, hlavně v kriminálkách a dobrodružných snímcích — nejznámější rolí zůstal Paulo v Melvillově Bobu Flamboyantovi (1956) a Fifi ve snímku Ruce na grisbi (1954). V roce 1964 si zahrál i v prvním Četníkovi ze Saint-Tropez. Později se přeorientoval na režii reklamních spotů — pod jeho vedením vznikly i francouzské reklamní klasiky pro značky Ovomaltine nebo Panzani, za které získal řadu ocenění včetně několika Zlatých lvů. Zemřel v roce 2020 ve věku 90 let na covid-19.",
    funFact: "Jeho synem je herec Didier Cauchy, který hrál kapitána Scandellu v seriálu La Crim' — spolu s otcem dokonce nahráli společnou desku pod hlavičkou vydavatelství Eddieho Barclaye.",
    filmography: [
      { year: 2000, title: "Les Acteurs" },
      { year: 1977, title: "La Fille d'Amérique" },
      { year: 1973, title: "Le Gang des otages" },
      { year: 1970, title: "Le Cœur fou" },
      { year: 1964, title: "Le Gendarme de Saint-Tropez" },
      { year: 1963, title: "D'où viens-tu Johnny ?" },
      { year: 1963, title: "Mathias Sandorf" },
      { year: 1962, title: "Arsène Lupin contre Arsène Lupin" },
      { year: 1962, title: "Les Ennemis" },
      { year: 1961, title: "Samedi soir" },
      { year: 1960, title: "Les Mordus" },
      { year: 1960, title: "Sergent X" },
      { year: 1959, title: "Les Fruits du péché" },
      { year: 1959, title: "J'irai cracher sur vos tombes" },
      { year: 1959, title: "Ça n'arrive qu'aux vivants" },
      { year: 1958, title: "Sacrée Jeunesse" },
      { year: 1958, title: "Miss Pigalle" },
      { year: 1958, title: "En légitime défense" },
      { year: 1957, title: "Police judiciaire" },
      { year: 1956, title: "Bob le flambeur" },
      { year: 1955, title: "Impasse des vertus" },
      { year: 1955, title: "Les Nuits de Montmartre" },
      { year: 1955, title: "Le Dossier noir" },
      { year: 1955, title: "Interdit de séjour" },
      { year: 1954, title: "Les Impures" },
      { year: 1954, title: "Le Comte de Monte-Cristo" },
      { year: 1954, title: "Touchez pas au grisbi" },
      { year: 1954, title: "Huis clos" },
      { year: 1953, title: "Suivez cet homme" },
      { year: 1953, title: "Le Portrait de son père" },
      { year: 1953, title: "Maternité clandestine" },
      { year: 1953, title: "Quand tu liras cette lettre" },
      { year: 1952, title: "Le Plus heureux des hommes" },
      { year: 1952, title: "Le Rideau rouge" },
      { year: 1952, title: "Cet âge est sans pitié" },
      { year: 1952, title: "Le Gantelet vert" },
      { year: 1952, title: "L'Amour, Madame" },
      { year: 1951, title: "Nous irons à Monte-Carlo" },
    ],
  },
  {
    slug: "nicole-vervil",
    name: "Nicole Vervil",
    category: "herec",
    birthYear: 1920,
    deathYear: 2005,
    nationality: "Francie",
    bio: "Nicole Vervil, vlastním jménem Thérèse Marguerite Le Carpentier, se narodila v Paříži. Po druhé světové válce se věnovala divadlu a zpěvu, k filmu se ale dostala až po čtyřicítce díky režisérovi Jeanu Giraultovi, který jí nabídl první roli v komedii Poslíčci (1961) po boku Darryho Cowla. Girault si ji pak vzpomněl i při obsazování první četnické komedie a svěřil jí roli paní Gerberové, ledově klidné manželky velitele četnické stanice (Michel Galabru) — tu si zahrála ve všech prvních třech dílech série, Četník ze Saint-Tropez (1964), Četník se žení (1968) a Četník ve výslužbě (1970). Spolu s Galabruem a Louisem de Funèsem se pak ještě potkala ve filmu Tonoucí se stébla chytá Roberta Dhéryho. Většinu jejích rolí tvořily komické postavy služebných, jeptišek, starých panen nebo ustaraných matek, jen výjimečně dostala příležitost i v dramatu (Doznání, Vědět zakázáno). Naposledy se objevila na plátně v roce 1974 ve filmu Francie, akciová společnost, pak se věnovala hlavně dabingu po boku svého manžela, herce Philippa Dumata. Zemřela v roce 2005 v normandském Coutances ve věku 84 let.",
    funFact: "Její kultovní hláška z prvního setkání s Cruchotem — „Ne, to prosím ne, paní velitelová… Gerberová, nebo Cecílie, to si vyberte“ — patří dodnes k nejcitovanějším scénkám celé četnické série.",
    funFactSourceUrl:
      "https://medium.seznam.cz/clanek/lucie-stiborova-nicole-vervil-pani-gerberova-z-cetnika-ze-saint-tropez-v-mladi-zpivala-pozdeji-hlavne-dabovala-312130",
    filmography: [
      { year: 1976, title: "12 úkolů pro Asterixe" },
      { year: 1974, title: "France société anonyme" },
      { year: 1973, title: "Défense de savoir" },
      { year: 1971, title: "La Cavale" },
      { year: 1970, title: "Četník ve výslužbě" },
      { year: 1970, title: "Doznání" },
      { year: 1969, title: "L'Américain" },
      { year: 1968, title: "Četník se žení" },
      { year: 1967, title: "Tonoucí se stébla chytá" },
      { year: 1964, title: "Četník ze Saint Tropez" },
      { year: 1961, title: "Les Livreurs" },
      { year: 1981, title: "Buď zdráv, šampióne!", note: "TV seriál" },
      { year: 1976, title: "Comme du bon pain", note: "TV seriál" },
      { year: 1973, title: "Un homme, une ville", note: "TV seriál" },
      { year: 1972, title: "Les Boussardel", note: "TV seriál" },
    ],
  },
];

export function findMockPerson(slug: string): MockPerson | undefined {
  return MOCK_PERSONS.find((p) => p.slug === slug);
}
