// Reserve catalog — personalities pulled out of persons.ts on 2026-09-26
// because they had neither a photo nor an Aukro/eBay price estimate yet
// (Aukro is a Czech marketplace, so there's no Czech-market price to find
// for these). Kept here rather than deleted so the researched bios,
// filmographies and sources aren't lost — bring an entry back into
// MOCK_PERSONS once it has a photo or a price for whichever market
// (fr/en) ends up covering it. Not imported anywhere; excluded from the
// live catalog on purpose.
import type { MockPerson } from "./persons";

export const RESERVED_PERSONS: MockPerson[] = [
  {
    slug: "nicole-vervil",
    name: "Nicole Vervil",
    category: "herec",
    gender: "f",
    birthYear: 1920,
    deathYear: 2005,
    nationality: "Francie",
    bio: "Nicole Vervil, vlastním jménem Thérèse Marguerite Le Carpentier, se narodila v Paříži. Po druhé světové válce se věnovala divadlu a zpěvu, k filmu se ale dostala až po čtyřicítce díky režisérovi Jeanu Giraultovi, který jí nabídl první roli v komedii Poslíčci (1961) po boku Darryho Cowla. Girault si ji pak vzpomněl i při obsazování první četnické komedie a svěřil jí roli paní Gerberové, ledově klidné manželky velitele četnické stanice (Michel Galabru) — tu si zahrála ve všech prvních třech dílech série, Četník ze Saint-Tropez (1964), Četník se žení (1968) a Četník ve výslužbě (1970). Spolu s Galabruem a Louisem de Funèsem se pak ještě potkala ve filmu Tonoucí se stébla chytá Roberta Dhéryho. Většinu jejích rolí tvořily komické postavy služebných, jeptišek, starých panen nebo ustaraných matek, jen výjimečně dostala příležitost i v dramatu (Doznání, Vědět zakázáno). Naposledy se objevila na plátně v roce 1974 ve filmu Francie, akciová společnost, pak se věnovala hlavně dabingu po boku svého manžela, herce Philippa Dumata. Zemřela v roce 2005 v normandském Coutances ve věku 84 let.",
    funFact: "Její kultovní hláška z prvního setkání s Cruchotem — „Ne, to prosím ne, paní velitelová… Gerberová, nebo Cecílie, to si vyberte“ — patří dodnes k nejcitovanějším scénkám celé četnické série.",
    funFactSourceUrl:
      "https://medium.seznam.cz/clanek/lucie-stiborova-nicole-vervil-pani-gerberova-z-cetnika-ze-saint-tropez-v-mladi-zpivala-pozdeji-hlavne-dabovala-312130",
    filmography: [
      { year: 1976, title: "12 úkolů pro Asterixe" },
      { year: 1974, title: "France société anonyme" },
      { year: 1973, title: "Défense de savoir" },
      { year: 1971, title: "La Cavale" },
      { year: 1970, title: "Četník ve výslužbě" },
      { year: 1970, title: "Doznání" },
      { year: 1969, title: "L'Américain" },
      { year: 1968, title: "Četník se žení" },
      { year: 1967, title: "Tonoucí se stébla chytá" },
      { year: 1964, title: "Četník ze Saint Tropez" },
      { year: 1961, title: "Les Livreurs" },
      { year: 1981, title: "Buď zdráv, šampióne!", note: "TV seriál" },
      { year: 1976, title: "Comme du bon pain", note: "TV seriál" },
      { year: 1973, title: "Un homme, une ville", note: "TV seriál" },
      { year: 1972, title: "Les Boussardel", note: "TV seriál" },
    ],
  },
  {
    slug: "alice-sapritch",
    name: "Alice Sapritchová",
    category: "herec",
    gender: "f",
    birthYear: 1916,
    deathYear: 1990,
    nationality: "Francie",
    bio: "Alice Sapritchová se narodila arménské rodině v Istanbulu, kde její otec navzdory chudobě způsobené hráčskými dluhy učil francouzštinu na proslulé škole Galatasaray. V třinácti letech odešla s matkou do Bruselu, v šestnácti sama do Paříže, kde si nejdřív vydělávala jako modelka pro sochaře a malíře. Po pařížské konzervatoři hrála menší filmové role po celá 50. léta, skutečný úspěch jí ale přinesla až televize — adaptace klasiků jako Balzacova Bratrance Betty nebo Barbey d'Aurevillyho román. Filmovou slávu si vysloužila paradoxně až v pětapadesáti letech, v roce 1971, komickou rolí přísné dvorní dámy doni Juany ve filmu Pošetilost mocných po boku Louise de Funèse a Yvesa Montanda — scéna jejího svůdného striptýzu patří dodnes k nejcitovanějším momentům francouzské filmové komedie. Zemřela v březnu 1990 v Paříži ve věku 73 let.",
    funFact:
      "Do filmové branže se dostala přes manžela, scenáristu Guillauma Hanoteaua, který pro ni napsal její úplně první filmovou roli v roce 1950 — rozvedli se po jednadvaceti letech manželství, krátce po natáčení Pošetilosti mocných, kvůli jeho nevěře.",
    filmography: [
      { year: 1971, title: "Pošetilost mocných" },
      { year: 1960, title: "Le Testament d'Orphée" },
      { year: 1960, title: "Tirez sur le pianiste" },
      { year: 1958, title: "Premier mai" },
    ],
  },
  {
    slug: "dominique-zardi",
    name: "Dominique Zardi",
    category: "herec",
    gender: "m",
    birthYear: 1930,
    deathYear: 2009,
    nationality: "Francie",
    bio: "Dominique Zardi, vlastním jménem Émile Cohen-Zardi, byl podle vlastních slov „králem třetích nožů“ francouzského filmu — objevil se v přes šesti stovkách filmů, ve třech stovkách z nich dokonce bez uvedení v titulcích. Nejčastěji hrál v tandemu se svým celoživotním parťákem Henrim Attalem, se kterým vytvořil neodmyslitelnou dvojici gaunerů a pohůnků v desítkách de Funèsových filmů, včetně celé fantomasovské trilogie. Byl také oblíbeným hercem režisérů Clauda Chabrola, Jeana-Pierra Mockyho a Pierra Granier-Deferra. Kromě herectví psal romány, skládal filmovou hudbu a texty písní, zejména pro Chabrolovy filmy. Zemřel na rakovinu v prosinci 2009 v Paříži ve věku 79 let.",
    funFact:
      "Na otázku, proč do svých filmů pořád obsazuje „třetí nože“ jako Zardiho a Attala, měl režisér André Hunebelle jasnou odpověď: „Víte, na kýtě není dobré maso, ale hřebíčky.“ — s odkazem na výrok herce Raimu.",
    filmography: [
      { year: 1971, title: "Jo" },
      { year: 1970, title: "Četník ve výslužbě" },
      { year: 1967, title: "Fantomas kontra Scotland Yard" },
      { year: 1965, title: "Fantomas se zlobí" },
      { year: 1964, title: "Fantomas" },
      { year: 1959, title: "Les Bonnes Femmes" },
    ],
  },
  {
    slug: "henri-attal",
    name: "Henri Attal",
    category: "herec",
    gender: "m",
    birthYear: 1936,
    deathYear: 2003,
    nationality: "Francie",
    bio: "Henri Attal se — sám nebo v nerozlučné dvojici s Dominiquem Zardim — objevil ve víc než stopadesáti filmech, téměř vždy ve vedlejších rolích gaunerů, pohůnků a pouličních povalečů. Debutoval u Clauda Chabrola ve filmu Dobré ženy (1959) a pravidelně se pak vracel do filmů Jeana-Luca Godarda, André Hunebella i Louise de Funèse, jehož fantomasovskou trilogii i pozdější komedie prošpikoval malými, ale nezaměnitelnými rolemi. Zemřel v červenci 2003 na astmatický záchvat v severofrancouzském Cucq ve věku 67 let.",
    funFact:
      "Ke svému celoživotnímu parťákovi Dominiqui Zardimu, se kterým hrál desítky filmů po boku, se přidal i na jeho poslední cestu — Zardi byl mezi truchlícími na Attalově pohřbu.",
    filmography: [
      { year: 1978, title: "Jeden hot a druhý čehý" },
      { year: 1965, title: "Fantomas se zlobí" },
      { year: 1964, title: "Fantomas" },
      { year: 1961, title: "Une femme est une femme" },
      { year: 1959, title: "Les Bonnes Femmes" },
    ],
  },
  {
    slug: "claude-pieplu",
    name: "Claude Piéplu",
    category: "herec",
    gender: "m",
    birthYear: 1923,
    deathYear: 2006,
    nationality: "Francie",
    bio: "Claude Piéplu se proslavil svým nezaměnitelným pomalým, mírně nadneseným přednesem a suchým humorem — jako čtrnáctiletý začínal jako poslíček v bance, kde pobaveně pozoroval a napodoboval kolegy. Po angažmá v divadelní společnosti Jacquesa Fabbriho odehrál přes sto sedmdesát pět divadelních her a čtyřicítku filmů, mimo jiné po boku Louise de Funèse, kterému sekundoval jako generální sekretář ministerstva vnitra v Hibernatovi (1969) nebo jako komisař Andréani v Dobrodružství rabína Jákoba (1973). Nejširšímu publiku je ale znám jako vypravěč kultovního animovaného seriálu Šadokové a jako „muž se zlatými klíči“ v seriálu Palace. Zemřel v květnu 2006 v Paříži ve věku 83 let.",
    funFact:
      "Jeho charakteristický, pomalu odměřovaný hlas se stal nedílnou součástí kultovního animovaného seriálu Šadokové, kde po celá desetiletí komentoval absurdní osudy nešikovných ptáků — pro celou jednu generaci francouzských diváků je to jeho nejznámější role.",
    filmography: [
      { year: 1973, title: "Dobrodružství rabína Jákoba" },
      { year: 1969, title: "Hibernatus" },
    ],
  },
  {
    slug: "julien-guiomar",
    name: "Julien Guiomar",
    category: "herec",
    gender: "m",
    birthYear: 1928,
    deathYear: 2010,
    nationality: "Francie",
    bio: "Julien Guiomar prošel klasickým hereckým školením v Národním lidovém divadle Jeana Vilara a ve filmu se prosadil v polovině 60. let, nejdřív ve vážných a drsných rolích — jako brutální řecký plukovník četnictva ve slavném politickém dramatu Z (1969) Costa-Gavrase. Od 70. let se přeorientoval hlavně na komedie, kde si vybudoval pověst autoritářského a nepříjemného typu — zahrál si i po boku Louise de Funèse dvakrát, jako průmyslník Jacques Tricatel v Křidýlku nebo stehýnku (1976) a jako doktor Landry v Jeden hot a druhý čehý (1978). Objevil se i v italských filmech a po boku Jeana-Paula Belmonda a Alaina Delona ve snímku Borsalino. Zemřel v listopadu 2010 v Agenu ve věku 82 let.",
    funFact:
      "Než se stal hercem, uvažoval o kariéře zubaře jako jeho otec — k herectví ho nakonec přivedly hodiny u Pierra Renoira, syna slavného malíře.",
    filmography: [
      { year: 1978, title: "Jeden hot a druhý čehý" },
      { year: 1976, title: "Křidýlko nebo stehýnko" },
      { year: 1970, title: "Borsalino" },
      { year: 1969, title: "Z" },
    ],
  },
  {
    slug: "claude-giraud",
    name: "Claude Giraud",
    category: "herec",
    gender: "m",
    birthYear: 1936,
    deathYear: 2020,
    nationality: "Francie",
    bio: "Claude Giraud patřil k sociétářům Comédie-Française, kde hrál velké role klasického repertoáru — Alcesta z Molièrova Misantropa nebo Macbetha. Filmovým divákům je nejznámější jako markýz Philippe de Plessis-Bellière ze slavné série o Angelice a jako revolucionář Mohamed Larbi Slimane, který v Dobrodružství rabína Jákoba (1973) vtáhne Louise de Funèse do víru arabské revoluce. Byl také vyhledávaným dabérem — francouzským hlasem Roberta Redforda, Tommyho Lee Jonese nebo Alana Rickmana, a namluvil Odyssea v animovaném seriálu Ulysse 31. Zemřel v listopadu 2020 v Clermont-Ferrandu ve věku 84 let.",
    funFact:
      "Byl dlouholetým francouzským dabingovým hlasem hollywoodských hvězd jako Robert Redford, Tommy Lee Jones nebo Alan Rickman — diváci ve Francii tak jeho hlas znali z desítek filmů, aniž by ho na plátně vůbec viděli.",
    filmography: [
      { year: 1973, title: "Dobrodružství rabína Jákoba" },
      { year: 1964, title: "Angelika a král" },
    ],
  },
  {
    slug: "daniel-ceccaldi",
    name: "Daniel Ceccaldi",
    category: "herec",
    gender: "m",
    birthYear: 1927,
    deathYear: 2003,
    nationality: "Francie",
    bio: "Daniel Ceccaldi byl korsického původu a herectví ho zaujalo už na gymnáziu Henriho IV. v Paříži, kde hrál v Molièrově Misantropovi. Na plátně debutoval v roce 1948 ve filmu Sachy Guitryho a zvučnou roli dostal už v roce 1954 v La Reine Margot po boku Jeanne Moreauové. Nejvíc je ale spjatý s postavou Luciena Darbona, otce Christine (Claude Jadeové), ve dvou filmech Françoise Truffauta, Ukradené polibky a Domácí štěstí — a s rolí drobného podvodníčka Peda Caselliho ve filmu Pouic-Pouic (1963) po boku Louise de Funèse. Zemřel v březnu 2003 ve Villejuif ve věku 75 let.",
    funFact:
      "Jeho role otce Christine ve dvou filmech Françoise Truffauta z něj udělala jednu z nejrozpoznatelnějších tváří francouzské „nové vlny“, přestože sám patřil spíš ke starší generaci bulvárních divadelních herců.",
    filmography: [
      { year: 1970, title: "Domicile conjugal" },
      { year: 1968, title: "Baisers volés" },
      { year: 1964, title: "L'Homme de Rio" },
      { year: 1963, title: "Pouic-Pouic" },
    ],
  },
  {
    slug: "guy-trejan",
    name: "Guy Tréjan",
    category: "herec",
    gender: "m",
    birthYear: 1921,
    deathYear: 2001,
    nationality: "Francie",
    bio: "Guy Tréjan, vlastním jménem Guy Treichler, byl francouzsko-švýcarský herec, který za druhé světové války unikl nucené práci v Německu s falešnými doklady přes Belgii do Švýcarska, kde pak osm let budoval divadelní kariéru. Do Paříže se vrátil na počátku 50. let a stal se vyhledávaným divadelním hercem — v roce 1991 dostal cenu Molière za roli v Náměstí hrdinů. Filmovým divákům je znám jako boháč Antoine Brévin, nápadník Mireille Darcové, ve filmu Pouic-Pouic (1963) po boku Louise de Funèse, se kterým si o osm let později zahrál i ve filmu Jo. Zemřel v lednu 2001 v Paříži ve věku 79 let.",
    funFact:
      "Umělecké jméno Tréjan si vymyslel spojením prvních tří písmen otcova příjmení Treichler a matčina dívčího jména Jamsin — vzniklo tak přes mezistupeň „Trejam“ jeho definitivní scénické jméno.",
    filmography: [
      { year: 1971, title: "Jo" },
      { year: 1963, title: "Pouic-Pouic" },
    ],
  },
  {
    slug: "francoise-christophe",
    name: "Françoise Christopheová",
    category: "herec",
    gender: "f",
    birthYear: 1923,
    deathYear: 2012,
    nationality: "Francie",
    bio: "Françoise Christopheová studovala u Reného Simona a na pařížské konzervatoři, odkud v roce 1948 odešla rovnou do Comédie-Française. Na divadle ztvárnila velké role klasického repertoáru, od Lucrezie Borgie po Roxanu z Cyrana z Bergeracu. Ve filmu debutovala ve 40. letech a pokračovala v aktivní kariéře až do vysokého věku — po boku Louise de Funèse a Jeana Maraise si zahrála lady Dorothée Mac Rashleyovou ve třetím díle fantomasovské trilogie, Fantomas kontra Scotland Yard (1967). Zemřela v lednu 2012 v Paříži ve věku 88 let.",
    funFact:
      "Její mladší sestra Paule-Marie se také stala herečkou, ovšem pod jiným jménem — Paule Emanuele — takže mnoho diváků netušilo, že jde o sestry.",
    filmography: [{ year: 1967, title: "Fantomas kontra Scotland Yard" }],
  },
  {
    slug: "henri-serre",
    name: "Henri Serre",
    category: "herec",
    gender: "m",
    birthYear: 1931,
    deathYear: 2023,
    nationality: "Francie",
    bio: "Henri Serre se proslavil rolí Jima po boku Jeanne Moreauové a Oskara Wernera ve slavném milostném trojúhelníku Jules a Jim (1962) Françoise Truffauta — role, která ho navždy spojila s francouzskou novou vlnou. Předtím v 50. letech zpíval v duu Suc et Serre v pařížských kabaretech na levém břehu Seiny. Ve filmu Fantomas kontra Scotland Yard (1967) po boku Louise de Funèse a Jeana Maraise ztvárnil André Berthiera, sekretáře skotského lorda. Zemřel v říjnu 2023 v Aveyronu ve věku 92 let.",
    funFact:
      "Se svým synem Martinem, který jako dítě hrál v Berriho krátkém filmu Le Poulet, natočil o desítky let později televizní seriál Mon fils, kde si zahráli otce a syna — tentokrát ale v opačných rolích, než jaké prožili ve skutečném životě.",
    filmography: [
      { year: 1967, title: "Fantomas kontra Scotland Yard" },
      { year: 1962, title: "Jules et Jim" },
    ],
  },
  {
    slug: "venantino-venantini",
    name: "Venantino Venantini",
    category: "herec",
    gender: "m",
    birthYear: 1930,
    deathYear: 2018,
    nationality: "Itálie",
    bio: "Venantino Venantini se původně chtěl stát malířem a kvůli studiu na pařížské Škole krásných umění si přivydělával jako komparzista ve velkofilmech jako Quo vadis nebo Ben Hur. Herectví ho postupně vtáhlo natolik, že se stal vyhledávaným charakterním hercem jak v Itálii (u režisérů jako Ettore Scola nebo Dino Risi), tak ve Francii, kde pravidelně spolupracoval s Georgesem Lautnerem a Gérardem Ourym. Louise de Funèse doprovázel hned v několika filmech — jako gangster Mickey ve Smolaři (1965), jako Enrique v Grand restaurantu pana Septima (1966) i jako markýz del Basto v Pošetilosti mocných (1971). Zemřel v říjnu 2018 v italském Viterbu ve věku 88 let.",
    funFact:
      "Do filmu se dostal čistě z finančních důvodů — jako mladý malíř studující v Paříži si přivydělával komparzováním ve velkofilmech Quo vadis a Ben Hur, než ho herectví pohltilo natrvalo.",
    filmography: [
      { year: 1971, title: "Pošetilost mocných" },
      { year: 1966, title: "Grand restaurant pana Septima" },
      { year: 1965, title: "Smolař" },
      { year: 1963, title: "Tontons flingueurs" },
    ],
  },
  {
    slug: "renzo-montagnani",
    name: "Renzo Montagnani",
    category: "herec",
    gender: "m",
    birthYear: 1930,
    deathYear: 1997,
    nationality: "Itálie",
    bio: "Renzo Montagnani se původně chystal na dráhu lékárníka, divadlo ho ale zlákalo natolik, že se po studiích přestěhoval do Říma za hereckou kariérou. V Itálii se stal populární tváří komediálního žánru, včetně kontroverzních, ale komerčně úspěšných „erotických komedií“ 70. let. Francouzským divákům je nejznámější jako krutý plukovník Farès, který v Dobrodružství rabína Jákoba (1973) pronásleduje Louise de Funèse. Zemřel v květnu 1997 v Římě ve věku 66 let.",
    funFact:
      "V Itálii ho proslavily hlavně komediální role ve „erotických komediích“ 70. let, přestože sám měl ambice na vážnější herectví — ve Francii ho naopak diváci znají jen z jediné, ale výrazné role padoucha v Dobrodružství rabína Jákoba.",
    filmography: [{ year: 1973, title: "Dobrodružství rabína Jákoba" }],
  },
  {
    slug: "franco-fabrizi",
    name: "Franco Fabrizi",
    category: "herec",
    gender: "m",
    birthYear: 1916,
    deathYear: 1995,
    nationality: "Itálie",
    bio: "Franco Fabrizi se z rodné Emilie-Romagne vydal do světa nejdřív jako model pro fotoromány, než ho objevil režisér Michelangelo Antonioni pro svůj film Kronika jedné lásky (1950). Zahrál si i ve slavném Felliniho filmu I vitelloni (1953), kde ztvárnil povrchního sukničkáře Fausta — roli, která definovala velkou část jeho pozdější kariéry. Za víc než čtyřicet let natočil přes sto dvacet filmů, mimo jiné italského podnikatele Marcella Cacciapuotiho ve francouzské komedii Tonoucí se stébla chytá (1968) po boku Louise de Funèse. Zemřel v říjnu 1995 v rodném Cortemaggiore ve věku 79 let.",
    funFact:
      "Postavu povrchního sukničkáře Fausta z Felliniho filmu I vitelloni hrál tak přesvědčivě, že mu podobné role provázely velkou část zbytku kariéry — včetně role italského konkurenta ve francouzské komedii Tonoucí se stébla chytá.",
    filmography: [
      { year: 1968, title: "Tonoucí se stébla chytá" },
      { year: 1953, title: "I vitelloni" },
      { year: 1950, title: "Cronaca di un amore" },
    ],
  },
  {
    slug: "folco-lulli",
    name: "Folco Lulli",
    category: "herec",
    gender: "m",
    birthYear: 1912,
    deathYear: 1970,
    nationality: "Itálie",
    bio: "Folco Lulli, syn operního barytonisty a bratr herce Piera Lulliho, se za druhé světové války zapojil do protifašistického odboje v italských horách, než se po válce naplno věnoval herectví. Stal se výrazným charakterním hercem italského poválečného filmu, mimo jiné ve slavném thrilleru Mzda strachu (1953) po boku Yvese Montanda. Francouzským divákům je znám jako jihoamerický prezident Novalès, který zmizí přímo z restaurace pana Septima v komedii Grand restaurant pana Septima (1966) po boku Louise de Funèse. Zemřel v květnu 1970 v Římě ve věku 57 let.",
    funFact:
      "Než se naplno věnoval herectví, bojoval za druhé světové války v italských horách po boku partyzánů-„Modrých“, pojmenovaných podle blankytných šátků ušitých z hedvábí seshozených padáků se zásobami.",
    filmography: [
      { year: 1966, title: "Grand restaurant pana Septima" },
      { year: 1953, title: "Mzda strachu" },
    ],
  },
  {
    slug: "alberto-de-mendoza",
    name: "Alberto de Mendoza",
    category: "herec",
    gender: "m",
    birthYear: 1923,
    deathYear: 2011,
    nationality: "Argentina",
    bio: "Alberto de Mendoza byl argentinský herec, který většinu kariéry strávil ve španělských a italských žánrových filmech — hororech, westernech i thrillerech. Francouzským divákům je nejznámější jako španělský král Karel II. v komedii Pošetilost mocných (1971) po boku Louise de Funèse a Yvesa Montanda, roli, na kterou vzpomínal ještě desítky let po natáčení. Zemřel v prosinci 2011 v Madridu ve věku 88 let.",
    funFact:
      "Ještě v roce 2010, skoro čtyřicet let po natáčení, se s viditelnou náklonností vracel ve vzpomínkách k natáčení Pošetilosti mocných po boku Louise de Funèse — přestože zbytek kariéry strávil hlavně ve španělských a italských žánrových filmech.",
    filmography: [
      { year: 1971, title: "Pošetilost mocných" },
      { year: 1965, title: "L'Arme à gauche" },
    ],
  },
  {
    slug: "gerard-rinaldi",
    name: "Gérard Rinaldi",
    category: "herec",
    gender: "m",
    birthYear: 1943,
    deathYear: 2012,
    nationality: "Francie",
    bio: "Gérard Rinaldi se coby student pařížského lycea Charlemagne věnoval jazzu na saxofon, než v roce 1963 potkal baskytaristu Jeana Sarruse a jeho kapelu Les Rebelles — sax nakonec vyhrál nad plánovanou dráhou novináře nebo pilota. Se skupinou, později přejmenovanou na Les Problèmes a nakonec na Les Charlots, se od roku 1966 stal jednou z nejpopulárnějších komediálních kapel Francie, proslulou parodickými písněmi jako Paulette, la reine des paupiettes nebo Merci Patron. Od roku 1970 do roku 1992 si zahrál ve čtrnácti filmech Charlotů, prakticky vždy jako charismatický „Gérard“ — mimo jiné v Bláznivých bažantech, Bláznech ze stadiónu, Velkém bazaru i Bažantech kontra Dracula. Byl skupině věrný od jejího založení až do roku 1986 a znovu se s ní vrátil v letech 2007–2011. Vedle hraní byl i vyhledávaným dabérem — řadu let propůjčoval hlas kreslenému Kulišákovi (Goofymu) v disneyovkách i videohrách Kingdom Hearts. Zemřel v březnu 2012 ve věku 69 let.",
    funFact:
      "Roli Kulišáka (Goofyho) daboval tak dlouho a důsledně, že se jeho hlas pro celou generaci francouzských diváků a hráčů videoher stal neoddělitelnou součástí postavy — vedle filmové kariéry u Charlotů jde o jeho nejrozšířenější dílo.",
    filmography: [
      { year: 1984, title: "Nebezpečné známosti" },
      { year: 1983, title: "Návrat bažantů" },
      { year: 1980, title: "Bažanti kontra Dracula" },
      { year: 1979, title: "Les Charlots en délire" },
      { year: 1978, title: "Bažanti a cizinecká legie" },
      { year: 1975, title: "Polibky z Hongkongu" },
      { year: 1974, title: "Čtyři sluhové a kardinál" },
      { year: 1974, title: "Čtyři sluhové a čtyři mušketýři" },
      { year: 1974, title: "Bažanti jdou do boje" },
      { year: 1973, title: "Velký bazar" },
      { year: 1972, title: "Blázni ze stadiónu" },
      { year: 1972, title: "Bažanti jedou do Španělska" },
      { year: 1971, title: "Blázniví bažanti" },
      { year: 1970, title: "La Grande Java" },
    ],
  },
  {
    slug: "gerard-filippelli",
    name: "Gérard Filippelli",
    category: "herec",
    gender: "m",
    birthYear: 1942,
    deathYear: 2021,
    nationality: "Francie",
    bio: "Gérard Filippelli, přezdívaný v kapele „Phil“, se naučil hrát na kytaru sám — nástroj koupil v roce 1964 od amerického vojáka v Châteauroux. V roce 1966 byl uváděčem sedadel v pařížském kině Grand Rex, když ho Jean Sarrus a Gérard Rinaldi přizvali jako zvukového technika ke kapele, která se brzy přejmenovala na Les Charlots. Byl u skupiny od jejího založení až do roku 1997 a odehrál patnáct jejích filmů — hlavní roli dostal ve filmu Bažanti kontra Dracula (1980). Zemřel na rakovinu v březnu 2021 v Argenteuil ve věku 78 let.",
    funFact:
      "Jeho první kytaru — koupenou v roce 1964 od amerického vojáka v Châteauroux za pět set tehdejších franků — se naučil hrát sám, bez jediné hodiny.",
    filmography: [
      { year: 1992, title: "Le Retour des Charlots" },
      { year: 1984, title: "Nebezpečné známosti" },
      { year: 1983, title: "Návrat bažantů" },
      { year: 1980, title: "Bažanti kontra Dracula" },
      { year: 1979, title: "Les Charlots en délire" },
      { year: 1978, title: "Bažanti a cizinecká legie" },
      { year: 1975, title: "Polibky z Hongkongu" },
      { year: 1974, title: "Čtyři sluhové a kardinál" },
      { year: 1974, title: "Čtyři sluhové a čtyři mušketýři" },
      { year: 1974, title: "Bažanti jdou do boje" },
      { year: 1973, title: "Velký bazar" },
      { year: 1972, title: "Blázni ze stadiónu" },
      { year: 1972, title: "Bažanti jedou do Španělska" },
      { year: 1971, title: "Blázniví bažanti" },
      { year: 1970, title: "La Grande Java" },
    ],
  },
  {
    slug: "luis-rego",
    name: "Luis Rego",
    category: "herec",
    gender: "m",
    birthYear: 1944,
    deathYear: null,
    nationality: "Portugalsko",
    bio: "Luis Rego uprchl v sedmnácti letech z portugalské diktatury, aby se vyhnul vojenské službě v Angole — při jedné z cest zpátky do vlasti byl za dezerci na dva měsíce uvězněn. Ve Francii se živil jako kytarista skupiny Les Problèmes, doprovázející zpěváka Antoina, a s přejmenováním na Les Charlots v roce 1966 se stal jedním ze zakládajících členů. Po natáčení Bláznivých bažantů (1971) skupinu opustil ze strachu, že zůstane navždy jen „jedním z Charlotů“ — přesto se do dalších jejich filmů ještě příležitostně vracel. Sólovou kariéru pak budoval jako herec (Dovolená po francouzsku, 1978) i jako spoluautor divadelní hry Viens chez moi, j'habite chez une copine, podle níž natočil film Patrice Leconte.",
    funFact:
      "Jeho uvěznění portugalským Salazarovým režimem za dezerci inspirovalo píseň Ballade à Luis Rego, prisonnier politique, kterou mu na podporu věnovala vlastní kapela Les Problèmes.",
    filmography: [
      { year: 1992, title: "Le Retour des Charlots" },
      { year: 1984, title: "La Vengeance du serpent à plumes" },
      { year: 1983, title: "Le Retour des bidasses en folie" },
      { year: 1978, title: "Dovolená po francouzsku" },
      { year: 1971, title: "Blázniví bažanti" },
      { year: 1970, title: "La Grande Java" },
    ],
  },
  {
    slug: "richard-bonnot",
    name: "Richard Bonnot",
    category: "herec",
    gender: "m",
    birthYear: 1957,
    deathYear: 2025,
    nationality: "Francie",
    bio: "Richard Bonnot se jako dítě naučil hrát na klavír a později i na kytaru a bicí, a po konzervatoři v Dijonu se stal učitelem hudby na základní škole. Souběžně hrával po barech a klubech — a když v roce 1986 Gérard Rinaldi opustil Les Charlots, aby se věnoval sólové herecké kariéře, zbylí dva členové Phil a Jean mu nabídli, aby se stal jeho nástupcem. Ve skupině zůstal do roku 1997 a znovu se k ní po Rinaldiho smrti přidal při reunion vystoupeních mezi lety 2014 a 2025. Zemřel v říjnu 2025 v Paříži ve věku 67 let.",
    funFact:
      "Než se stal profesionálním hudebníkem, učil hudbu na základní škole v Saône-et-Loire — angažmá u Charlotů přijal až po vítězném účinkování v televizní pěvecké soutěži Les habits du dimanche, ve jejímž finále porazil budoucího zpěváka Patricka Fioriho.",
    filmography: [{ year: 1992, title: "Le Retour des Charlots" }],
  },
];
