-- Seed the real `persons` catalog table from lib/mockData/persons.ts.
-- All rows are pre-vetted content (bios, filmography etc. live in code for
-- now — see mockData's own header), so they're inserted as status =
-- 'approved' directly, matching how portraits (0004) already skip a
-- moderation queue for the same reason. Run as the SQL editor / postgres
-- role, which bypasses RLS, same as every other migration here.
--
-- Idempotent: re-running only inserts rows for new slugs.
--
-- Review before running; this is not applied automatically.

insert into persons (slug, name, category, birth_year, death_year, nationality, portrait_commons_file, portrait_author, portrait_license, portrait_source_url, status)
values
  ('louis-de-funes', 'Louis de Funès', 'actor', 1914, 1983, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/DeFunes-1953-Harcourt.jpg?width=480', 'Studio Harcourt', 'Volné dílo (Francie) — kolektivní dílo staré přes 70 let', 'https://commons.wikimedia.org/wiki/File:DeFunes-1953-Harcourt.jpg', 'approved'),
  ('michel-galabru', 'Michel Galabru', 'actor', 1922, 2016, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/Galabru-1952-Harcourt.jpg?width=480', 'Studio Harcourt', 'Volné dílo (Francie) — kolektivní dílo staré přes 70 let', 'https://commons.wikimedia.org/wiki/File:Galabru-1952-Harcourt.jpg', 'approved'),
  ('jean-lefebvre', 'Jean Lefebvre', 'actor', 1919, 2004, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/JeanLefebvre-1963-Harcourt.png?width=480', 'Studio Harcourt', 'Volné dílo (Francie) — kolektivní dílo staré přes 70 let', 'https://commons.wikimedia.org/wiki/File:JeanLefebvre-1963-Harcourt.png', 'approved'),
  ('genevieve-gradova', 'Geneviève Gradová', 'actor', 1944, 2024, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/Genevi%C3%A8ve_Grad_Sandokan_1963.jpg?width=480', 'filmová produkce (Sandokan Veliký, 1963)', 'Volné dílo (Itálie) — promlčená ochranná lhůta', 'https://commons.wikimedia.org/wiki/File:Genevi%C3%A8ve_Grad_Sandokan_1963.jpg', 'approved'),
  ('christian-marin', 'Christian Marin', 'actor', 1929, 2012, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/Christian_Marin_1965.jpg?width=480', 'Farabola agency, Milán', 'Volné dílo (Itálie) — promlčená ochranná lhůta', 'https://commons.wikimedia.org/wiki/File:Christian_Marin_1965.jpg', 'approved'),
  ('guy-grosso', 'Guy Grosso', 'actor', 1933, 2001, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/Guy-Grosso-1965-Crayon_3.png?width=480', 'Tisourcier (kresba podle dobové fotografie)', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Guy-Grosso-1965-Crayon_3.png', 'approved'),
  ('france-rumilly', 'France Rumilly', 'actor', 1939, null, 'Francie', null, null, null, null, 'approved'),
  ('michel-modo', 'Michel Modo', 'actor', 1937, 2008, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/MichelModo-1965-crayon.png?width=480', 'Tisourcier (kresba podle dobové fotografie)', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:MichelModo-1965-crayon.png', 'approved'),
  ('daniel-cauchy', 'Daniel Cauchy', 'actor', 1930, 2020, 'Francie', 'https://commons.wikimedia.org/wiki/Special:FilePath/Daniel_Cauchy.jpg?width=480', 'Christian Attard', 'CC BY-SA 4.0', 'https://commons.wikimedia.org/wiki/File:Daniel_Cauchy.jpg', 'approved'),
  ('claude-gensacova', 'Claude Gensacová', 'actor', 1927, 2016, 'Francie', null, null, null, null, 'approved'),
  ('paul-preboist', 'Paul Préboist', 'actor', 1927, 1997, 'Francie', null, null, null, null, 'approved'),
  ('bourvil', 'Bourvil', 'actor', 1917, 1970, 'Francie', null, null, null, null, 'approved'),
  ('jean-marais', 'Jean Marais', 'actor', 1913, 1998, 'Francie', null, null, null, null, 'approved'),
  ('mylene-demongeot', 'Mylène Demongeotová', 'actor', 1935, 2022, 'Francie', null, null, null, null, 'approved'),
  ('mireille-darc', 'Mireille Darcová', 'actor', 1938, 2017, 'Francie', null, null, null, null, 'approved'),
  ('jacqueline-maillan', 'Jacqueline Maillanová', 'actor', 1923, 1992, 'Francie', null, null, null, null, 'approved'),
  ('bernard-blier', 'Bernard Blier', 'actor', 1916, 1989, 'Francie', null, null, null, null, 'approved'),
  ('olivier-de-funes', 'Olivier de Funès', 'actor', 1949, null, 'Francie', null, null, null, null, 'approved'),
  ('claude-rich', 'Claude Rich', 'actor', 1929, 2017, 'Francie', null, null, null, null, 'approved'),
  ('yves-montand', 'Yves Montand', 'actor', 1921, 1991, 'Francie', null, null, null, null, 'approved'),
  ('annie-girardot', 'Annie Girardotová', 'actor', 1931, 2011, 'Francie', null, null, null, null, 'approved'),
  ('coluche', 'Coluche', 'actor', 1944, 1986, 'Francie', null, null, null, null, 'approved'),
  ('jean-carmet', 'Jean Carmet', 'actor', 1920, 1994, 'Francie', null, null, null, null, 'approved'),
  ('jacques-villeret', 'Jacques Villeret', 'actor', 1951, 2005, 'Francie', null, null, null, null, 'approved'),
  ('maurice-risch', 'Maurice Risch', 'actor', 1943, null, 'Francie', null, null, null, null, 'approved'),
  ('patrick-prejean', 'Patrick Préjean', 'actor', 1944, null, 'Francie', null, null, null, null, 'approved'),
  ('jean-pierre-rambal', 'Jean-Pierre Rambal', 'actor', 1931, 2001, 'Francie', null, null, null, null, 'approved'),
  ('yves-vincent', 'Yves Vincent', 'actor', 1921, 2016, 'Francie', null, null, null, null, 'approved'),
  ('jacques-dynam', 'Jacques Dynam', 'actor', 1923, 2004, 'Francie', null, null, null, null, 'approved'),
  ('pierre-tornade', 'Pierre Tornade', 'actor', 1930, 2012, 'Francie', null, null, null, null, 'approved'),
  ('pierre-repp', 'Pierre Repp', 'actor', 1909, 1986, 'Francie', null, null, null, null, 'approved'),
  ('mario-david', 'Mario David', 'actor', 1927, 1996, 'Francie', null, null, null, null, 'approved'),
  ('michael-lonsdale', 'Michael Lonsdale', 'actor', 1931, 2020, 'Francie', null, null, null, null, 'approved'),
  ('miou-miou', 'Miou-Miou', 'actor', 1950, null, 'Francie', null, null, null, null, 'approved'),
  ('terry-thomas', 'Terry-Thomas', 'actor', 1911, 1990, 'Velká Británie', null, null, null, null, 'approved'),
  ('marcel-dalio', 'Marcel Dalio', 'actor', 1899, 1983, 'Francie', null, null, null, null, 'approved'),
  ('lambert-wilson', 'Lambert Wilson', 'actor', 1958, null, 'Francie', null, null, null, null, 'approved'),
  ('pierre-dac', 'Pierre Dac', 'actor', 1893, 1975, 'Francie', null, null, null, null, 'approved'),
  ('popeck', 'Popeck', 'actor', 1935, null, 'Francie', null, null, null, null, 'approved'),
  ('jean-roger-caussimon', 'Jean-Roger Caussimon', 'actor', 1918, 1985, 'Francie', null, null, null, null, 'approved'),
  ('suzy-delair', 'Suzy Delairová', 'actor', 1917, 2020, 'Francie', null, null, null, null, 'approved'),
  ('henri-guybet', 'Henri Guybet', 'actor', 1936, null, 'Francie', null, null, null, null, 'approved'),
  ('raymond-bussieres', 'Raymond Bussières', 'actor', 1907, 1982, 'Francie', null, null, null, null, 'approved'),
  ('robert-dhery', 'Robert Dhéry', 'actor', 1921, 2004, 'Francie', null, null, null, null, 'approved'),
  ('noel-roquevert', 'Noël Roquevert', 'actor', 1892, 1973, 'Francie', null, null, null, null, 'approved'),
  ('robert-dalban', 'Robert Dalban', 'actor', 1903, 1987, 'Francie', null, null, null, null, 'approved'),
  ('marie-dubois', 'Marie Duboisová', 'actor', 1937, 2014, 'Francie', null, null, null, null, 'approved'),
  ('babeth-etienne', 'Babeth Étienneová', 'actor', 1957, null, 'Francie', null, null, null, null, 'approved'),
  ('catherine-serre', 'Catherine Serreová', 'actor', 1954, null, 'Francie', null, null, null, null, 'approved'),
  ('sophie-michaud', 'Sophie Michaudová', 'actor', 1962, null, 'Francie', null, null, null, null, 'approved'),
  ('nicaise-jean-louis', 'Nicaise Jean-Louis', 'actor', 1946, null, 'Francie', null, null, null, null, 'approved'),
  ('jean-sarrus', 'Jean Sarrus', 'actor', 1945, 2025, 'Francie', null, null, null, null, 'approved'),
  ('jean-guy-fechner', 'Jean-Guy Fechner', 'actor', 1947, null, 'Francie', null, null, null, null, 'approved'),
  ('gerard-jugnot', 'Gérard Jugnot', 'actor', 1951, null, 'Francie', null, null, null, null, 'approved'),
  ('gerard-depardieu', 'Gérard Depardieu', 'actor', 1948, null, 'Francie', null, null, null, null, 'approved'),
  ('pierre-richard', 'Pierre Richard', 'actor', 1934, null, 'Francie', null, null, null, null, 'approved'),
  ('zdenek-sverak', 'Zdeněk Svěrák', 'actor', 1936, null, 'Česko', null, null, null, null, 'approved'),
  ('ladislav-smoljak', 'Ladislav Smoljak', 'actor', 1931, 2010, 'Česko', null, null, null, null, 'approved'),
  ('jiri-sovak', 'Jiří Sovák', 'actor', 1920, 2000, 'Česko', null, null, null, null, 'approved'),
  ('josef-kemr', 'Josef Kemr', 'actor', 1922, 1995, 'Česko', null, null, null, null, 'approved'),
  ('josef-abrham', 'Josef Abrhám', 'actor', 1939, 2022, 'Česko', null, null, null, null, 'approved'),
  ('iva-janzurova', 'Iva Janžurová', 'actor', 1941, null, 'Česko', null, null, null, null, 'approved'),
  ('libuse-safrankova', 'Libuše Šafránková', 'actor', 1953, 2021, 'Česko', null, null, null, null, 'approved'),
  ('jan-triska', 'Jan Tříska', 'actor', 1936, 2017, 'Česko', null, null, null, null, 'approved'),
  ('daniela-kolarova', 'Daniela Kolářová', 'actor', 1946, null, 'Česko', null, null, null, null, 'approved'),
  ('ondrej-vetchy', 'Ondřej Vetchý', 'actor', 1962, null, 'Česko', null, null, null, null, 'approved'),
  ('oldrich-kaiser', 'Oldřich Kaiser', 'actor', 1955, null, 'Česko', null, null, null, null, 'approved'),
  ('alena-vranova', 'Alena Vránová', 'actor', 1932, null, 'Česko', null, null, null, null, 'approved'),
  ('vladimir-raz', 'Vladimír Ráž', 'actor', 1923, 2000, 'Česko', null, null, null, null, 'approved'),
  ('milos-kopecky', 'Miloš Kopecký', 'actor', 1922, 1996, 'Česko', null, null, null, null, 'approved'),
  ('stanislav-neumann', 'Stanislav Neumann', 'actor', 1902, 1975, 'Česko', null, null, null, null, 'approved'),
  ('jaroslav-senik', 'Jaroslav Seník', 'actor', 1897, 1957, 'Česko', null, null, null, null, 'approved'),
  ('jana-werichova', 'Jana Werichová', 'actor', 1935, 1981, 'Česko', null, null, null, null, 'approved'),
  ('jan-werich', 'Jan Werich', 'actor', 1905, 1980, 'Česko', null, null, null, null, 'approved'),
  ('vlasta-burian', 'Vlasta Burian', 'actor', 1891, 1962, 'Česko', null, null, null, null, 'approved'),
  ('milena-dvorska', 'Milena Dvorská', 'actor', 1938, 2009, 'Česko', null, null, null, null, 'approved'),
  ('miroslav-hornicek', 'Miroslav Horníček', 'actor', 1918, 2003, 'Česko', null, null, null, null, 'approved'),
  ('marie-glazrova', 'Marie Glázrová', 'actor', 1911, 2000, 'Česko', null, null, null, null, 'approved'),
  ('josef-bek', 'Josef Bek', 'actor', 1918, 1995, 'Česko', null, null, null, null, 'approved'),
  ('eva-klepacova', 'Eva Klepáčová', 'actor', 1933, 2012, 'Česko', null, null, null, null, 'approved'),
  ('frantisek-smolik', 'František Smolík', 'actor', 1891, 1972, 'Česko', null, null, null, null, 'approved'),
  ('ladislav-pesek', 'Ladislav Pešek', 'actor', 1906, 1986, 'Česko', null, null, null, null, 'approved'),
  ('frantisek-filipovsky', 'František Filipovský', 'actor', 1907, 1993, 'Česko', null, null, null, null, 'approved'),
  ('josef-beyvl', 'Josef Beyvl', 'actor', 1906, 1978, 'Česko', null, null, null, null, 'approved'),
  ('eman-fiala', 'Eman Fiala', 'actor', 1899, 1970, 'Česko', null, null, null, null, 'approved'),
  ('josef-hlinomaz', 'Josef Hlinomaz', 'actor', 1914, 1978, 'Česko', null, null, null, null, 'approved'),
  ('martin-ruzek', 'Martin Růžek', 'actor', 1918, 1995, 'Česko', null, null, null, null, 'approved'),
  ('marie-kyselkova', 'Marie Kyselková', 'actor', 1935, 2019, 'Česko', null, null, null, null, 'approved'),
  ('josef-zima', 'Josef Zíma', 'actor', 1932, 2025, 'Česko', null, null, null, null, 'approved'),
  ('jarmila-kurandova', 'Jarmila Kurandová', 'actor', 1890, 1978, 'Česko', null, null, null, null, 'approved'),
  ('josef-vinklar', 'Josef Vinklář', 'actor', 1930, 2007, 'Česko', null, null, null, null, 'approved'),
  ('rudolf-hrusinsky', 'Rudolf Hrušínský', 'actor', 1920, 1994, 'Česko', null, null, null, null, 'approved'),
  ('vaclav-lohnisky', 'Václav Lohniský', 'actor', 1920, 1980, 'Česko', null, null, null, null, 'approved'),
  ('bela-jurdova', 'Běla Jurdová', 'actor', 1919, 2009, 'Česko', null, null, null, null, 'approved'),
  ('bohus-zahorsky', 'Bohuš Záhorský', 'actor', 1906, 1980, 'Česko', null, null, null, null, 'approved'),
  ('otakar-brousek', 'Otakar Brousek', 'actor', 1924, 2014, 'Česko', null, null, null, null, 'approved'),
  ('helena-vondrackova', 'Helena Vondráčková', 'actor', 1947, null, 'Česko', null, null, null, null, 'approved'),
  ('vaclav-neckar', 'Václav Neckář', 'actor', 1943, null, 'Česko', null, null, null, null, 'approved'),
  ('jaroslav-marvan', 'Jaroslav Marvan', 'actor', 1901, 1974, 'Česko', null, null, null, null, 'approved'),
  ('stella-zazvorkova', 'Stella Zázvorková', 'actor', 1922, 2005, 'Česko', null, null, null, null, 'approved'),
  ('pavel-travnicek', 'Pavel Trávníček', 'actor', 1950, null, 'Česko', null, null, null, null, 'approved'),
  ('vladimir-mensik', 'Vladimír Menšík', 'actor', 1929, 1988, 'Česko', null, null, null, null, 'approved'),
  ('dana-hlavacova', 'Dana Hlaváčová', 'actor', 1945, null, 'Česko', null, null, null, null, 'approved'),
  ('jan-libicek', 'Jan Libíček', 'actor', 1931, 1974, 'Česko', null, null, null, null, 'approved'),
  ('petr-stepanek', 'Petr Štěpánek', 'actor', 1948, null, 'Česko', null, null, null, null, 'approved'),
  ('jorga-kotrbova', 'Jorga Kotrbová', 'actor', 1947, 2025, 'Česko', null, null, null, null, 'approved'),
  ('marie-rosulkova', 'Marie Rosůlková', 'actor', 1901, 1993, 'Česko', null, null, null, null, 'approved'),
  ('luba-skorepova', 'Luba Skořepová', 'actor', 1923, 2016, 'Česko', null, null, null, null, 'approved'),
  ('miroslava-safrankova', 'Miroslava Šafránková', 'actor', 1958, null, 'Česko', null, null, null, null, 'approved'),
  ('radovan-lukavsky', 'Radovan Lukavský', 'actor', 1919, 2008, 'Česko', null, null, null, null, 'approved'),
  ('petr-svojtka', 'Petr Svojtka', 'actor', 1946, 1982, 'Česko', null, null, null, null, 'approved'),
  ('dagmar-patrasova', 'Dagmar Patrasová', 'actor', 1956, null, 'Česko', null, null, null, null, 'approved'),
  ('nada-konvalinkova', 'Naďa Konvalinková', 'actor', 1951, null, 'Česko', null, null, null, null, 'approved'),
  ('helena-ruzickova', 'Helena Růžičková', 'actor', 1936, 2004, 'Česko', null, null, null, null, 'approved'),
  ('jiri-korn', 'Jiří Korn', 'actor', 1949, null, 'Česko', null, null, null, null, 'approved'),
  ('marie-horakova', 'Marie Horáková', 'actor', 1959, null, 'Česko', null, null, null, null, 'approved'),
  ('jan-hrusinsky', 'Jan Hrušínský', 'actor', 1955, null, 'Česko', null, null, null, null, 'approved'),
  ('libuse-svormova', 'Libuše Švormová', 'actor', 1935, null, 'Česko', null, null, null, null, 'approved'),
  ('dana-vavrova', 'Dana Vávrová', 'actor', 1967, 2009, 'Česko', null, null, null, null, 'approved'),
  ('lubomir-lipsky', 'Lubomír Lipský', 'actor', 1923, 2015, 'Česko', null, null, null, null, 'approved'),
  ('vlastimil-brodsky', 'Vlastimil Brodský', 'actor', 1920, 2002, 'Česko', null, null, null, null, 'approved'),
  ('vlastimil-harapes', 'Vlastimil Harapes', 'actor', 1946, 2024, 'Česko', null, null, null, null, 'approved'),
  ('vaclav-voska', 'Václav Voska', 'actor', 1918, 1982, 'Česko', null, null, null, null, 'approved'),
  ('jana-brejchova', 'Jana Brejchová', 'actor', 1940, 2026, 'Česko', null, null, null, null, 'approved'),
  ('ludek-munzar', 'Luděk Munzar', 'actor', 1933, 2019, 'Česko', null, null, null, null, 'approved'),
  ('jana-hlavacova', 'Jana Hlaváčová', 'actor', 1938, 2024, 'Česko', null, null, null, null, 'approved'),
  ('jiri-bartoska', 'Jiří Bartoška', 'actor', 1947, 2025, 'Česko', null, null, null, null, 'approved'),
  ('vladimir-dlouhy', 'Vladimír Dlouhý', 'actor', 1958, 2010, 'Česko', null, null, null, null, 'approved'),
  ('viktor-preiss', 'Viktor Preiss', 'actor', 1947, null, 'Česko', null, null, null, null, 'approved'),
  ('petr-narozny', 'Petr Nárožný', 'actor', 1938, null, 'Česko', null, null, null, null, 'approved'),
  ('karel-hermanek', 'Karel Heřmánek', 'actor', 1947, 2024, 'Česko', null, null, null, null, 'approved'),
  ('vera-tichankova', 'Věra Tichánková', 'actor', 1920, 2014, 'Česko', null, null, null, null, 'approved'),
  ('michaela-kuklova', 'Michaela Kuklová', 'actor', 1968, null, 'Česko', null, null, null, null, 'approved'),
  ('jan-potmesil', 'Jan Potměšil', 'actor', 1966, 2026, 'Česko', null, null, null, null, 'approved'),
  ('lubor-tokos', 'Lubor Tokoš', 'actor', 1923, 2003, 'Česko', null, null, null, null, 'approved'),
  ('jirina-bohdalova', 'Jiřina Bohdalová', 'actor', 1931, null, 'Česko', null, null, null, null, 'approved'),
  ('filip-blazek', 'Filip Blažek', 'actor', 1973, null, 'Česko', null, null, null, null, 'approved'),
  ('jaromir-hanzlik', 'Jaromír Hanzlík', 'actor', 1948, null, 'Česko', null, null, null, null, 'approved'),
  ('jiri-labus', 'Jiří Lábus', 'actor', 1950, null, 'Česko', null, null, null, null, 'approved'),
  ('zdenek-stepanek', 'Zdeněk Štěpánek', 'actor', 1896, 1968, 'Česko', null, null, null, null, 'approved'),
  ('alfred-strejcek', 'Alfred Strejček', 'actor', 1941, null, 'Česko', null, null, null, null, 'approved'),
  ('radoslav-brzobohaty', 'Radoslav Brzobohatý', 'actor', 1932, 2012, 'Česko', null, null, null, null, 'approved'),
  ('zlata-adamovska', 'Zlata Adamovská', 'actor', 1959, null, 'Česko', null, null, null, null, 'approved'),
  ('julie-juristova', 'Julie Jurištová', 'actor', 1955, null, 'Česko', null, null, null, null, 'approved'),
  ('michal-dlouhy', 'Michal Dlouhý', 'actor', 1968, null, 'Česko', null, null, null, null, 'approved'),
  ('ivana-chylkova', 'Ivana Chýlková', 'actor', 1963, null, 'Česko', null, null, null, null, 'approved'),
  ('boris-rosner', 'Boris Rösner', 'actor', 1951, 2006, 'Česko', null, null, null, null, 'approved'),
  ('ondrej-pavelka', 'Ondřej Pavelka', 'actor', 1955, null, 'Česko', null, null, null, null, 'approved'),
  ('josef-somr', 'Josef Somr', 'actor', 1934, 2022, 'Česko', null, null, null, null, 'approved'),
  ('martina-navratilova', 'Martina Navrátilová', 'athlete', 1956, null, 'Česko', null, null, null, null, 'approved'),
  ('ivan-lendl', 'Ivan Lendl', 'athlete', 1960, null, 'Česko', null, null, null, null, 'approved'),
  ('jana-novotna', 'Jana Novotná', 'athlete', 1968, 2017, 'Česko', null, null, null, null, 'approved'),
  ('petra-kvitova', 'Petra Kvitová', 'athlete', 1990, null, 'Česko', null, null, null, null, 'approved'),
  ('tomas-berdych', 'Tomáš Berdych', 'athlete', 1985, null, 'Česko', null, null, null, null, 'approved'),
  ('pavel-nedved', 'Pavel Nedvěd', 'athlete', 1972, null, 'Česko', null, null, null, null, 'approved'),
  ('antonin-panenka', 'Antonín Panenka', 'athlete', 1948, null, 'Česko', null, null, null, null, 'approved'),
  ('josef-masopust', 'Josef Masopust', 'athlete', 1931, 2015, 'Česko', null, null, null, null, 'approved'),
  ('petr-cech', 'Petr Čech', 'athlete', 1982, null, 'Česko', null, null, null, null, 'approved'),
  ('lukas-krpalek', 'Lukáš Krpálek', 'athlete', 1990, null, 'Česko', null, null, null, null, 'approved'),
  ('martin-doktor', 'Martin Doktor', 'athlete', 1974, null, 'Česko', null, null, null, null, 'approved'),
  ('stepanka-hilgertova', 'Štěpánka Hilgertová', 'athlete', 1968, null, 'Česko', null, null, null, null, 'approved'),
  ('gabriela-koukalova', 'Gabriela Koukalová', 'athlete', 1989, null, 'Česko', null, null, null, null, 'approved'),
  ('ondrej-moravec', 'Ondřej Moravec', 'athlete', 1984, null, 'Česko', null, null, null, null, 'approved'),
  ('barbora-spotakova', 'Barbora Špotáková', 'athlete', 1981, null, 'Česko', null, null, null, null, 'approved'),
  ('zuzana-hejnova', 'Zuzana Hejnová', 'athlete', 1986, null, 'Česko', null, null, null, null, 'approved'),
  ('josef-dostal', 'Josef Dostál', 'athlete', 1993, null, 'Česko', null, null, null, null, 'approved'),
  ('ales-valenta', 'Aleš Valenta', 'athlete', 1973, null, 'Česko', null, null, null, null, 'approved'),
  ('emil-zatopek', 'Emil Zátopek', 'athlete', 1922, 2000, 'Česko', null, null, null, null, 'approved'),
  ('dana-zatopkova', 'Dana Zátopková', 'athlete', 1922, 2020, 'Česko', null, null, null, null, 'approved'),
  ('vera-caslavska', 'Věra Čáslavská', 'athlete', 1942, 2016, 'Česko', null, null, null, null, 'approved'),
  ('jiri-raska', 'Jiří Raška', 'athlete', 1941, 2012, 'Česko', null, null, null, null, 'approved'),
  ('katerina-neumannova', 'Kateřina Neumannová', 'athlete', 1973, null, 'Česko', null, null, null, null, 'approved'),
  ('jarmila-kratochvilova', 'Jarmila Kratochvílová', 'athlete', 1951, null, 'Česko', null, null, null, null, 'approved'),
  ('roman-sebrle', 'Roman Šebrle', 'athlete', 1974, null, 'Česko', null, null, null, null, 'approved'),
  ('zdenek-koubek', 'Zdeněk Koubek', 'athlete', 1913, 1986, 'Česko', null, null, null, null, 'approved'),
  ('ludvik-danek', 'Ludvík Daněk', 'athlete', 1937, 1998, 'Česko', null, null, null, null, 'approved'),
  ('jaromir-jagr', 'Jaromír Jágr', 'athlete', 1972, null, 'Česko', null, null, null, null, 'approved'),
  ('dominik-hasek', 'Dominik Hašek', 'athlete', 1965, null, 'Česko', null, null, null, null, 'approved'),
  ('ivan-hlinka', 'Ivan Hlinka', 'athlete', 1950, 2004, 'Česko', null, null, null, null, 'approved'),
  ('jiri-holik', 'Jiří Holík', 'athlete', 1944, null, 'Česko', null, null, null, null, 'approved'),
  ('patrik-elias', 'Patrik Eliáš', 'athlete', 1976, null, 'Česko', null, null, null, null, 'approved'),
  ('jaroslav-drobny', 'Jaroslav Drobný', 'athlete', 1921, 2001, 'Česko', null, null, null, null, 'approved'),
  ('milan-hnilicka', 'Milan Hnilička', 'athlete', 1973, null, 'Česko', null, null, null, null, 'approved'),
  ('petr-klima', 'Petr Klíma', 'athlete', 1964, 2023, 'Česko', null, null, null, null, 'approved'),
  ('frantisek-pospisil', 'František Pospíšil', 'athlete', 1944, null, 'Česko', null, null, null, null, 'approved')
on conflict (slug) do nothing;
